Texture { Albedo = 'P_GDL001.dds', Normal = 'P_GDL001_N.dds', Size = 2 }
Texture { Albedo = 'P_GDL002.dds', Normal = 'P_GDL002_N.dds', Size = 4 }
Texture { Albedo = 'P_GDM001.dds', Normal = 'P_GDM001_N.dds', Size = 2 }
Texture { Albedo = 'P_GDM002.dds', Normal = 'P_GDM002_N.dds', Size = 2 }
Texture { Albedo = 'P_GDS001.dds', Normal = 'P_GDS001_N.dds', Size = 1 }
Texture { Albedo = 'P_GDS002.dds', Normal = 'P_GDS002_N.dds', Size = 0.5 }
Texture { Albedo = 'P_GLL001.dds', Normal = 'P_GLL001_N.dds', Size = 4 }
Texture { Albedo = 'P_GLL002.dds', Normal = 'P_GLL002_N.dds', Size = 4 }
Texture { Albedo = 'P_GLM001.dds', Normal = 'P_GLM001_N.dds', Size = 2 }
Texture { Albedo = 'P_GLM002.dds', Normal = 'P_GLM002_N.dds', Size = 2 }
Texture { Albedo = 'P_GLM003.dds', Normal = 'P_GLM003_N.dds', Size = 2 }
Texture { Albedo = 'P_GLS001.dds', Normal = 'P_GLS001_N.dds', Size = 1 }
Texture { Albedo = 'P_GLS002.dds', Normal = 'P_GLS002_N.dds', Size = 0.5 }
Texture { Albedo = 'P_GBL001.dds', Normal = 'P_GBL001_N.dds', Size = 4 }
Texture { Albedo = 'P_GBL002.dds', Normal = 'P_GBL002_N.dds', Size = 4 }
Texture { Albedo = 'P_GBL003.dds', Normal = 'P_GBL003_N.dds', Size = 4 }
Texture { Albedo = 'P_GBM001.dds', Normal = 'P_GBM001_N.dds', Size = 2 }
Texture { Albedo = 'P_GBM002.dds', Normal = 'P_GBM002_N.dds', Size = 2 }