name = "RD's Rebalance"
uid = "29eda5ea-0a47-494e-b301-rdsrebalance"
version = '1.0'
copyright = "None"
description = "Aims to diversify the different factions to a higher degree."
author = "RD"
url = ""
icon = "/mods/LOUD.bmp"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }