name = "LOUD No Voiceover Alerts"
uid = "7be1d5f4-c544-11ea-87d0-noalerts0001"
version = 0
copyright = "© 2020"
description = "Disables the voiceover alerts and pings when ACUs are spotted, transports start ferry routes, and mass extractors come under attack."
author = "Gralzeim, script modified from original by Balthazar"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }