version = 3
ScenarioInfo = {
  name = 'Shards Balanced',
  description = '<LOC Shards_Description>The Aeon believed that this planet was blessed with The Way, and for generations they protected it from the presence of sentient life. Now that the Coalition is running low on resources, desperation has caused that restriction to be lifted.',
  type = 'skirmish',
  starts = true,
  preview = '',
  size = {2048, 2048},
  map = '/maps/Shards/Shards.scmap',
  map_version = 9,
  save = '/maps/Shards/Shards_balanced_save.lua',
  script = '/maps/Shards/Shards_script.lua',
  norushradius = 36,
  Configurations = {
    ['standard'] = {
      teams = {
        {
          name = 'FFA',
          armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8', 'ARMY_9', 'ARMY_10'},
          --armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8'},
        },
      },
      customprops = {},
    },
  },
  norushoffsetX_ARMY_1 = 0,
  norushoffsetY_ARMY_1 = 0,
  norushoffsetX_ARMY_2 = 0,
  norushoffsetY_ARMY_2 = 0,
  norushoffsetX_ARMY_3 = 0,
  norushoffsetY_ARMY_3 = 0,
  norushoffsetX_ARMY_4 = 0,
  norushoffsetY_ARMY_4 = 0,
  norushoffsetX_ARMY_5 = 0,
  norushoffsetY_ARMY_5 = 0,
  norushoffsetX_ARMY_6 = 0,
  norushoffsetY_ARMY_6 = 0,
  norushoffsetX_ARMY_7 = 0,
  norushoffsetY_ARMY_7 = 0,
  norushoffsetX_ARMY_8 = 0,
  norushoffsetY_ARMY_8 = 0,
}
