-- TOTAL MAYHEM Unit Descriptions --

Description['brmt1pd']		=	"The Slyfox outranges most T1 units, allowing it to hit first. It's tough, but a slow rate of fire limits its usefulness."
Description['brmt1expd']	=	"The Pen is the traditional Cybran beam weapon mounted on a solid gimble. Equally capable against air & ground units, the superior range and accuracy is offset by it's high cost"
Description['brmt1expdt2']	=	"Trying to get more from the Pen, the dual Pen offers more firepower but no AA ability versus its lighter brother. Very costly for its class."
Description['brmt2pd']		=	"The Slingshot is a traditional projectile weapon -- good range, power and a relatively robust frame make this a desirable but expensive alternative to the Cerberus."
Description['brmt2epd']		=	"The Anode is a superior PD system - unique in the use of a bubble shield, allowing it to trade armor for quick traverse and the ability to engage air targets. With its Hi-V railgun, the Anode is truly high-end, and high cost."
Description['brmt3pd']		=	"Nothing special; the Tripple is simply naval guns mounted on a heavily armored turret. Not particularily original for the Cybran, but functional."
Description['brmt3pdro']	=	"The Agronar is an effective long-range deterrent system. Capable of stunning all low and mid-tier units, it can stall and decimate an assault before it gets too close."
Description['brmt1bt']		=	"The Mite is a light amphibious tank with reasonable specs."
Description['brmt1exm1']	=	"The Proton is arguably the finest low-tier bot - quick and hard hitting with superior range for it's class."
Description['brmt2ht']		=	"The Hippo is an attempt to improve upon the Rhino. The addition of a Chaos rocket pack gives it some medium range striking power, but the stun effects are minimal."
Description['brmt2MEDM']	=	"The Immortal was designed to address the weaknesses of the Wagner for amphibious use. Tough and with medium range stand-off mortars, the costly Immortal can be a tough opponent."
Description['brmt3bm2']		= 	"The Dervish is the peak of Cybran bot tech. Speed for its size, amphibiousness, missile redirection, radar and a hard hitting weapons package that includes Chaos rockets, the Dervish can cause untold mayhem in short order."
Description['brmt3bt']		=	"The Mastodon is the most recent Cybran tank effort. While not a Super-heavy, it is economical, well balanced and well armed, and the tank fares well in its class."
Description['brmt3lzt']		=	"The Trilobyte brings the exceptional railgun of the Anode PD to a mobile platform. Designed to fill the need for amphibious AA support, the weapon is effective in both AA and ground roles, and the Trilobyte moves easily through water."
Description['brmst3bom']	=	"A modified battleship designed for long range high-arc bombardment rather than direct fire."
Description['brmt3vul']		=	"The Vulture is a small but cost effective experimental unit designed along the lines of the Loyalist as a quick raider."
Description['brmt3mcm2']	=	"The MadBolo is veritably an up-armoured and up-gunned Madcat. Be wary of its volatility."
Description['brmt3ava']		=	"The Avalanche is the largest mobile experimental ever constructed. Essentially a factory like the Megalith, it is ponderously slow, but extremely armored and well-gunned. Capable of surviving a direct strike even by tactical nukes."

Description['brnt3shpd-Radar_T3'] = "Installs a typical T3 radar package onto the unit."
Description['brnt3shpd-Shield'] = "Installs a custom Shield Dome into the unit."
Description['brnt3shpd-Regen'] = "Improves Regeneration rate."

Description['brot1bt']		=	"The Hervour is simply a larger Aurora. The same simple but effective configuration in a larger format. Sometimes hampered by its lack of a fully rotating turret."
Description['brot3shpd-Radar_T3'] = "Installs a typical T3 radar package onto the unit."
Description['brot3shpd-Shield'] = "Installs a custom Shield Dome into the unit."

Description['brpat3gunship']=	"Heavy Gunship similar to the Aeon Restorer. Heavily armed for Air to Ground and Air to Air, with thick armor - expensive and very slow."
Description['brpat2bomber']	=	"An upgraded and upsized true attack bomber. Reasonably quick and can deliver a decent payload, but fragile like all attack bombers."

Description['brpt1pd']		= 	"A small, but tough point defense weapon with a solid punch."
Description['brpt2pd']		= 	"A multirole point defense system capable against both ground and air targets. Rapid-firing."
Description['brpt3pd']		= 	"A simple but highly effective energy weapon in a robust shell. Excellent damage and range and substantial AOE gives it the ability to pulverize enemy units at range."
Description['brpexpd']		= 	"While not equipped with Lambda defenses, the slow-firing Ultrachromatic Beam makes short work of both ground and air targets, with the unusual ability to hit even orbital targets."
Description['brpt1exm1']	= 	"The most advanced bot in the Seraphim Tech 1 arsenal. Quick and powerful."
Description['brpt1ht']		= 	"Provides the Seraphim with an early amphibious option."
Description['brpt2btbot']	= 	"The Iltha is a beefed up version of the standard highly-regarded Ilshavoh - more armor, more firepower."
Description['brpat2figbo']	= 	"A true combat fighter equipped with dual autocannons. More nimble than any other true interceptor, the use of a projectile weapon instead of AA missiles hampers its value somewhat."
Description['brpt3bt']		= 	"The Hethaamah represents all that is good in Seraphim tracked units; a simple well-executed tank design."
Description['brpt3ml']		= 	"A somewhat unusual artillery support unit, Heth-Zthuha provides extraordinary fire coverage for a mobile unit via mediocre accuracy and large area-of-effect. Not effective for precise killing."
Description['brpt3bot']		= 	"Thaam-Thuum is the heaviest factory-produced bot available to the Seraphim. Amphibious, with massive armor, firepower and even air defense, its only real weakness is a limited arc for its primary weapons."
Description['brpextank']	= 	"Trying to build on the success of the Hethaamah, the Light Experimental Yath-Us is another fairly simple tank design, but this time amphibious, with massive armor and firepower."
Description['brpexbtbot']	= 	"Realizing a weakness in overall doctrine, the newly-seen Tha-Yath brings substantial AA, radar and good firepower in a Light Experimental package."
Description['brpexbot']		= 	"Yenoh-Iao is a Medium Experimental with good mobility and solid firepower."
Description['brpexhvbot']	= 	"Athusil, often also called Kali for its distinctive look, is a unique Medium Experimental fielded by the Seraphim. Apparently drawing its design from recent experiences, Athusil brings a unique blend of tools to the battlefield -- excellent AA, long range, and blistering knife-fighting tools make it very dangerous."
Description['brpexshbm']	= 	"This is a unique support unit, artillery, intel and counter-intel, with AA."