layout = {
	['sort-arrow-down_bmp'] = {left = 6, top = 6, width = 24, height = 16, },
	['sort-arrow-up_bmp'] = {left = 6, top = 6, width = 24, height = 16, },
	['sort_btn_down_r'] = {left = 83, top = 2, width = 12, height = 24, },
	['sort_btn_down_m'] = {left = 12, top = 2, width = 12, height = 24, },
	['sort_btn_down_l'] = {left = 2, top = 2, width = 12, height = 24, },
	['sort_btn_over_r'] = {left = 83, top = 2, width = 12, height = 24, },
	['sort_btn_over_m'] = {left = 12, top = 2, width = 12, height = 24, },
	['sort_btn_over_l'] = {left = 2, top = 2, width = 12, height = 24, },
	['sort_btn_up_r'] = {left = 83, top = 2, width = 12, height = 24, },
	['sort_btn_up_m'] = {left = 12, top = 2, width = 12, height = 24, },
	['sort_btn_up_l'] = {left = 2, top = 2, width = 12, height = 24, },
	['sort_btn_dis_r'] = {left = 83, top = 2, width = 12, height = 24, },
	['sort_btn_dis_m'] = {left = 12, top = 2, width = 12, height = 24, },
	['sort_btn_dis_l'] = {left = 2, top = 2, width = 12, height = 24, },
}
