layout = {
	['glow_bmp'] = {left = 4, top = 4, width = 48, height = 42, },
	['play_btn_selected'] = {left = 7, top = 7, width = 42, height = 36, },
	['play_btn_down'] = {left = 6, top = 6, width = 43, height = 37, },
	['play_btn_over'] = {left = 7, top = 7, width = 42, height = 36, },
	['play_btn_up'] = {left = 7, top = 7, width = 42, height = 36, },
	['play_btn_dis'] = {left = 7, top = 7, width = 42, height = 36, },
	['pause_btn_selected'] = {left = 7, top = 7, width = 42, height = 36, },
	['pause_btn_down'] = {left = 6, top = 6, width = 43, height = 37, },
	['pause_btn_over'] = {left = 7, top = 7, width = 42, height = 36, },
	['pause_btn_up'] = {left = 7, top = 7, width = 42, height = 36, },
	['pause_btn_dis'] = {left = 7, top = 7, width = 42, height = 36, },
	['diplomacy_btn_selected'] = {left = 7, top = 8, width = 42, height = 35, },
	['diplomacy_btn_down'] = {left = 6, top = 7, width = 43, height = 36, },
	['diplomacy_btn_over'] = {left = 7, top = 8, width = 42, height = 35, },
	['diplomacy_btn_up'] = {left = 7, top = 8, width = 42, height = 35, },
	['diplomacy_btn_dis'] = {left = 7, top = 8, width = 42, height = 35, },
	['objectives_btn_selected'] = {left = 7, top = 8, width = 42, height = 40, },
	['objectives_btn_down'] = {left = 6, top = 7, width = 43, height = 41, },
	['objectives_btn_over'] = {left = 7, top = 6, width = 42, height = 42, },
	['objectives_btn_up'] = {left = 7, top = 8, width = 42, height = 37, },
	['objectives_btn_dis'] = {left = 7, top = 8, width = 42, height = 35, },
	['menu_btn_selected'] = {left = 7, top = 6, width = 42, height = 37, },
	['menu_btn_down'] = {left = 6, top = 6, width = 43, height = 37, },
	['menu_btn_over'] = {left = 7, top = 3, width = 42, height = 40, },
	['menu_btn_up'] = {left = 7, top = 8, width = 42, height = 35, },
	['menu_btn_dis'] = {left = 7, top = 8, width = 42, height = 35, },
}
