version = 3
ScenarioInfo = {
  Configurations = {
    standard = {
      teams = {
        {
          armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8'},
          name = 'FFA',
        },
      },
    },
  },
  description = '<LOC Hellgate_Description>After the central caldera collapsed, and cooled, the conflict resumed.',
  map = '/maps/Hellgate/Hellgate.scmap',
  map_version = '1.1',
  name = 'Hellgate 40 - 8 Player',
  norushradius = 62,
  preview = '',
  save = '/maps/Hellgate/Hellgate_4 on 4_save.lua',
  script = '/maps/Hellgate/Hellgate_script.lua',
  size = {2048, 2048},
  starts = true,
  type = 'skirmish',
  norushoffsetX_ARMY_1 = 0,
  norushoffsetY_ARMY_1 = 0,
  norushoffsetX_ARMY_2 = 0,
  norushoffsetY_ARMY_2 = 0,
  norushoffsetX_ARMY_3 = 0,
  norushoffsetY_ARMY_3 = 0,
  norushoffsetX_ARMY_4 = 0,
  norushoffsetY_ARMY_4 = 0,
  norushoffsetX_ARMY_5 = 0,
  norushoffsetY_ARMY_5 = 0,
  norushoffsetX_ARMY_6 = 0,
  norushoffsetY_ARMY_6 = 0,
  norushoffsetX_ARMY_7 = 0,
  norushoffsetY_ARMY_7 = 0,
  norushoffsetX_ARMY_8 = 0,
  norushoffsetY_ARMY_8 = 0,
}
