layout = {
	['drag-handle-ur_btn_down'] = {left = 0, top = 3, width = 68, height = 93, },
	['drag-handle-ur_btn_over'] = {left = 0, top = 3, width = 68, height = 93, },
	['drag-handle-ur_btn_up'] = {left = 0, top = 5, width = 65, height = 91, },
	['drag-handle-ur_btn_dis'] = {left = 0, top = 5, width = 65, height = 91, },
	['drag-handle-ul_btn_down'] = {left = 14, top = 3, width = 66, height = 93, },
	['drag-handle-ul_btn_over'] = {left = 14, top = 3, width = 66, height = 93, },
	['drag-handle-ul_btn_up'] = {left = 17, top = 5, width = 63, height = 91, },
	['drag-handle-ul_btn_dis'] = {left = 17, top = 5, width = 63, height = 91, },
	['drag-handle-ll_btn_down'] = {left = 14, top = 0, width = 66, height = 93, },
	['drag-handle-ll_btn_over'] = {left = 14, top = 0, width = 66, height = 93, },
	['drag-handle-ll_btn_up'] = {left = 17, top = 0, width = 63, height = 91, },
	['drag-handle-ll_btn_dis'] = {left = 17, top = 0, width = 63, height = 91, },
	['drag-handle-lr_btn_down'] = {left = 0, top = 0, width = 68, height = 93, },
	['drag-handle-lr_btn_over'] = {left = 0, top = 0, width = 68, height = 93, },
	['drag-handle-lr_btn_up'] = {left = 0, top = 0, width = 65, height = 91, },
	['drag-handle-lr_btn_dis'] = {left = 0, top = 0, width = 65, height = 91, },
}
