name = "UI Party"
version = 15
copyright = "nah"
description = "Various UI Enhancements. With contributions from many."
author = "Anihilnine, with contributions (technical help / ideas / I stole their code) from Zock, Domino, Myxir, yorick, Sir Prize, Crotalus, Coding Squirrel, Morax, Speed2, Hotbuild, camelCase, HUSAR_PL, MaCielPL, tatsu, sheeo, icedreamer, JoonasTo, Heaven, Fast-Thick-Pants"
url = ""
uid = "022E3DB4-9C00-5ED7-9876-4866D316E015"
exclusive = false
ui_only = true
conflicts = {  }
requires = {"zcbf6277-24e3-437a-b968-Common-v1"}
before = {"zcbf6277-24e3-437a-b968-Common-v1"}
after = { }
