layout = {
	['nav-end_btn_down'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-end_btn_over'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-end_btn_up'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-end_btn_dis'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-rr_btn_down'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-rr_btn_over'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-rr_btn_up'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-rr_btn_dis'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-ff_btn_down'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-ff_btn_over'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-ff_btn_up'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-ff_btn_dis'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-pause_btn_down'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-pause_btn_over'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-pause_btn_up'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-pause_btn_dis'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-play_btn_down'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-play_btn_over'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-play_btn_up'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-play_btn_dis'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-back_btn_down'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-back_btn_over'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-back_btn_up'] = {left = 0, top = 0, width = 36, height = 36, },
	['nav-back_btn_dis'] = {left = 0, top = 0, width = 36, height = 36, },
}
