layout = {
	['bar-top_scr_down'] = {left = 7, top = 7, width = 22, height = 7, },
	['bar-top_scr_over'] = {left = 7, top = 7, width = 21, height = 7, },
	['bar-top_scr_up'] = {left = 7, top = 7, width = 21, height = 7, },
	['bar-top_scr_dis'] = {left = 7, top = 7, width = 22, height = 7, },
	['bar-mid_scr_down'] = {left = 7, top = 14, width = 22, height = 8, },
	['bar-mid_scr_over'] = {left = 7, top = 14, width = 21, height = 8, },
	['bar-mid_scr_up'] = {left = 7, top = 14, width = 21, height = 8, },
	['bar-mid_scr_dis'] = {left = 7, top = 14, width = 22, height = 8, },
	['bar-bot_scr_down'] = {left = 7, top = 22, width = 21, height = 7, },
	['bar-bot_scr_over'] = {left = 7, top = 22, width = 21, height = 7, },
	['bar-bot_scr_up'] = {left = 7, top = 22, width = 21, height = 7, },
	['bar-bot_scr_dis'] = {left = 7, top = 22, width = 21, height = 7, },
	['arrow-up_scr_down'] = {left = 3, top = 3, width = 29, height = 30, },
	['arrow-up_scr_over'] = {left = 4, top = 4, width = 28, height = 29, },
	['arrow-up_scr_up'] = {left = 4, top = 4, width = 28, height = 29, },
	['arrow-up_scr_dis'] = {left = 4, top = 4, width = 28, height = 29, },
	['arrow-down_scr_down'] = {left = 3, top = 3, width = 29, height = 30, },
	['arrow-down_scr_over'] = {left = 4, top = 4, width = 28, height = 29, },
	['arrow-down_scr_up'] = {left = 4, top = 4, width = 28, height = 29, },
	['arrow-down_scr_dis'] = {left = 4, top = 4, width = 28, height = 29, },
	['back_scr_top'] = {left = 4, top = 4, width = 27, height = 10, },
	['back_scr_mid'] = {left = 4, top = 14, width = 27, height = 8, },
}
