layout = {
	['units-select_icon_bmp_dis'] = {left = 11, top = 8, width = 35, height = 16, },
	['units-select_icon_bmp'] = {left = 8, top = 5, width = 41, height = 22, },
	['units-attached_icon_bmp_dis'] = {left = 11, top = 10, width = 35, height = 15, },
	['units-attached_icon_bmp'] = {left = 8, top = 8, width = 41, height = 20, },
	['enhance-back_icon_bmp_dis'] = {left = 17, top = 8, width = 23, height = 17, },
	['enhance-back_icon_bmp'] = {left = 15, top = 6, width = 27, height = 21, },
	['enhance-l-arm_icon_bmp_dis'] = {left = 15, top = 7, width = 28, height = 17, },
	['enhance-l-arm_icon_bmp'] = {left = 13, top = 5, width = 32, height = 21, },
	['enhance-r-arm_icon_bmp_dis'] = {left = 16, top = 7, width = 28, height = 17, },
	['enhance-r-arm_icon_bmp'] = {left = 14, top = 5, width = 32, height = 21, },
	['experimental_icon_bmp_dis'] = {left = 22, top = 6, width = 20, height = 19, },
	['experimental_icon_bmp'] = {left = 19, top = 2, width = 26, height = 26, },
	['tech-level-3_icon_bmp_dis'] = {left = 22, top = 6, width = 20, height = 19, },
	['tech-level-3_icon_bmp'] = {left = 19, top = 2, width = 26, height = 26, },
	['tech-level-2_icon_bmp_dis'] = {left = 22, top = 6, width = 20, height = 19, },
	['tech-level-2_icon_bmp'] = {left = 19, top = 2, width = 26, height = 26, },
	['tech-level-1_icon_bmp_dis'] = {left = 22, top = 6, width = 20, height = 19, },
	['tech-level-1_icon_bmp'] = {left = 19, top = 2, width = 26, height = 26, },
	['tech-tab_btn_over_sel'] = {left = 0, top = 0, width = 55, height = 32, },
	['tech-tab_btn_up_sel'] = {left = 0, top = 0, width = 55, height = 32, },
	['tech-tab_btn_over'] = {left = 1, top = 0, width = 54, height = 31, },
	['tech-tab_btn_up'] = {left = 0, top = 0, width = 55, height = 32, },
	['tech-tab_btn_dis'] = {left = 2, top = 1, width = 52, height = 29, },
}
