layout = {
	['ping_edge_yellow_glow'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_tr_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_tr_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_tr_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_tl_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_tl_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_tl_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_t_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_t_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_t_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_r_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_r_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_r_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_l _down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_l _over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_l _up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_br_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_br_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_br_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_bl_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_bl_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_bl_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_b_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_b_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_yellow_b_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_glow'] = {left = 1, top = 2, width = 50, height = 48, },
	['ping_edge_red_tr_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_tr_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_tr_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_tl_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_tl_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_tl_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_t_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_t_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_t_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_r_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_r_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_r_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_l _down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_l _over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_l _up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_br_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_br_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_br_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_bl_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_bl_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_bl_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_b_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_b_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_red_b_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_glow'] = {left = 1, top = 2, width = 50, height = 48, },
	['ping_edge_blue_tr_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_tr_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_tr_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_tl_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_tl_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_tl_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_t_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_t_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_t_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_r_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_r_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_r_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_l_down'] = {left = 0, top = 0, width = 37, height = 52, },
	['ping_edge_blue_l_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_l_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_br_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_br_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_br_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_bl_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_bl_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_bl_up'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_b_down'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_b_over'] = {left = 0, top = 0, width = 52, height = 52, },
	['ping_edge_blue_b_up'] = {left = 0, top = 0, width = 52, height = 52, },
}
