ScenarioInfo = {
  name = 'Seton\'s Clutch 40',
  type = 'skirmish',
  description = '<LOC setons clutch 40_Description>The Classic map - rebuilt as a 40km.',
  starts = true,
  preview = '',
  size = {2048, 2048},
  map_version = 11,
  norushradius = 60,
  map = '/maps/Setons Clutch 40/Setons Clutch 40.scmap',
  save = '/maps/Setons Clutch 40/Setons Clutch 40_save.lua',
  script = '/maps/Setons Clutch 40/Setons Clutch 40_script.lua',
  Configurations = {
    ['standard'] = {
      teams = {
        {
          name = 'FFA',
          --armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8'},
          armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8', 'ARMY_9', 'ARMY_10'},
        },
      },
      customprops = {
        ['ExtraArmies'] = STRING( 'ARMY_11 NEUTRAL_CIVILIAN' ),
      },
    },
  },
  norushoffsetX_ARMY_1 = 0,
  norushoffsetY_ARMY_1 = 0,
  norushoffsetX_ARMY_2 = 0,
  norushoffsetY_ARMY_2 = 0,
  norushoffsetX_ARMY_3 = 0,
  norushoffsetY_ARMY_3 = 0,
  norushoffsetX_ARMY_4 = 0,
  norushoffsetY_ARMY_4 = 0,
  norushoffsetX_ARMY_5 = 0,
  norushoffsetY_ARMY_5 = 0,
  norushoffsetX_ARMY_6 = 0,
  norushoffsetY_ARMY_6 = 0,
  norushoffsetX_ARMY_7 = 0,
  norushoffsetY_ARMY_7 = 0,
  norushoffsetX_ARMY_8 = 0,
  norushoffsetY_ARMY_8 = 0,
}
