name = "4th Dimension Units for LOUD"
uid = "454af309-5afb-458b-bf5b-a00000000007"
version = 6.3
copyright = "Copyright © 2010, Resin_Smoker, Optimus_Prime, Ebola_Soup, Vissroid"
description = "Selected 4th Dimension units for The LOUD Project"
author = "Resin_Smoker"
url = ""
icon = "/mods/4DC/Icon_4DC.png" 
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
requires = { }
requiresNames = { }
before = { }
after = { }
