name = "Tanksy's Experiments: Combat Reelism"
uid = "TANKSYS-EXPERIMENTS-1-COMBAT"
version = "1.2"
copyright = "None"
description = "A different combat experience: Up to 3x longer ranged weapons, adjusted ballistics, faster missiles, emphasised scouting and high-arc artillery."
author = "Tanksy"
url = ""
icon = "/mods/LOUD.bmp"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
