ScenarioInfo = {
  name = 'Thawing Glacier 40 - 6 on 3',
  description = '<LOC Thawing Glacier 40_Description>A trip to a bigger frozen landscape! Specially marked for a 6 vs. 3 AI configuration.  Best played with the ENHANCED AI UNIT CAP option turned on.',
  type = 'skirmish',
  starts = true,
  map_version = 2,
  preview = '',
  size = {2048, 2048},
  map = '/maps/Thawing Glacier 40/Thawing Glacier 40.scmap',
  save = '/maps/Thawing Glacier 40/Thawing Glacier 40_6 on 3_save.lua',
  script = '/maps/Thawing Glacier 40/Thawing Glacier 40_script.lua',
  norushradius = 72,
  Configurations = {
    ['standard'] = {
      teams = {
        {
          name = 'FFA',
          --armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8'},
          armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8', 'ARMY_9',},
        },
      },
    },
  },
  norushoffsetX_ARMY_1 = 0,
  norushoffsetY_ARMY_1 = 0,
  norushoffsetX_ARMY_2 = 0,
  norushoffsetY_ARMY_2 = 0,
  norushoffsetX_ARMY_3 = 0,
  norushoffsetY_ARMY_3 = 0,
  norushoffsetX_ARMY_4 = 0,
  norushoffsetY_ARMY_4 = 0,
  norushoffsetX_ARMY_5 = 0,
  norushoffsetY_ARMY_5 = 0,
  norushoffsetX_ARMY_6 = 0,
  norushoffsetY_ARMY_6 = 0,
  norushoffsetX_ARMY_7 = 0,
  norushoffsetY_ARMY_7 = 0,
  norushoffsetX_ARMY_8 = 0,
  norushoffsetY_ARMY_8 = 0,
}
