layout = {
	['set-sharing_btn_down'] = {left = 2, top = 2, width = 48, height = 40, },
	['set-sharing_btn_over'] = {left = 2, top = 2, width = 48, height = 40, },
	['set-sharing_btn_up'] = {left = 2, top = 2, width = 48, height = 40, },
	['set-sharing_btn_dis'] = {left = 2, top = 2, width = 48, height = 40, },
	['give-resource_btn_down'] = {left = 7, top = 7, width = 36, height = 32, },
	['give-resource_btn_over'] = {left = 7, top = 7, width = 36, height = 32, },
	['give-resource_btn_up'] = {left = 7, top = 7, width = 36, height = 32, },
	['give-resource_btn_dis'] = {left = 7, top = 7, width = 36, height = 32, },
	['give-unit_btn_down'] = {left = 7, top = 7, width = 36, height = 32, },
	['give-unit_btn_over'] = {left = 7, top = 7, width = 36, height = 32, },
	['give-unit_btn_up'] = {left = 7, top = 7, width = 36, height = 32, },
	['give-unit_btn_dis'] = {left = 7, top = 7, width = 36, height = 32, },
	['chat-observer_btn_down'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-observer_btn_over'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-observer_btn_up'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-observer_btn_dis'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-allies_btn_down'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-allies_btn_over'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-allies_btn_up'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-allies_btn_dis'] = {left = 2, top = 2, width = 48, height = 40, },
	['chat-all_btn_down'] = {left = 1, top = 2, width = 48, height = 40, },
	['chat-all_btn_over'] = {left = 1, top = 2, width = 48, height = 40, },
	['chat-all_btn_up'] = {left = 1, top = 2, width = 48, height = 40, },
	['chat-all_btn_dis'] = {left = 2, top = 2, width = 48, height = 40, },
}
