Texture { Albedo = 'P_GDL001.dds', Size = 2 }
Texture { Albedo = 'P_GDL002.dds', Size = 4 }
Texture { Albedo = 'P_GDM001.dds', Size = 2 }
Texture { Albedo = 'P_GDM002.dds', Size = 2 }
Texture { Albedo = 'P_GDS001.dds', Size = 1 }
Texture { Albedo = 'P_GDS002.dds', Size = 0.5 }
Texture { Albedo = 'P_GLL001.dds', Size = 4 }
Texture { Albedo = 'P_GLL002.dds', Size = 4 }
Texture { Albedo = 'P_GLM001.dds', Size = 2 }
Texture { Albedo = 'P_GLM002.dds', Size = 2 }
Texture { Albedo = 'P_GLM003.dds', Size = 2 }
Texture { Albedo = 'P_GLS001.dds', Size = 1 }
Texture { Albedo = 'P_GLS002.dds', Size = 0.5 }
Texture { Albedo = 'P_GBL001.dds', Size = 4 }
Texture { Albedo = 'P_GBL002.dds', Size = 4 }
Texture { Albedo = 'P_GBL003.dds', Size = 4 }
Texture { Albedo = 'P_GBM001.dds', Size = 2 }
Texture { Albedo = 'P_GBM002.dds', Size = 2 }