name = "Enhanced Static HP"
uid = "b8d941e131multiplier"
version = 6.3
copyright = ""
description = "All static units have health and shield points multiplied by number noted in config."
author = "Balthazar"
selectable = true
enabled = true
exclusive = false
ui_only = false
