layout = {
	['top_tab_btn_sel_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['top_tab_btn_down_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['top_tab_btn_over_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['top_tab_btn_up_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['top_tab_btn_dis_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['mid_tab_btn_sel_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['mid_tab_btn_down_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['mid_tab_btn_over_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['mid_tab_btn_up_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['mid_tab_btn_dis_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['bot_tab_btn_sel_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['bot_tab_btn_down_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['bot_tab_btn_over_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['bot_tab_btn_up_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
	['bot_tab_btn_dis_bmp'] = {left = 0, top = 0, width = 76, height = 56, },
}
