name = "Experimental Icons Overhaul"
uid = "2529ea71-93ef-41a6-b552-EXPERICON00005"
version = 0.6
copyright = "© 2015 Sean Wheeldon"
description = "An experimental icons overhaul - from BrewLAN."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN/documentation/BrewLAN-LOUD-full.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
