name = "Experimental Icons Overhaul from BrewLAN"
uid = "2529ea71-93ef-41a6-b552-EXPERICON00005"
version = 0.6
copyright = "� 2015 Sean Wheeldon"
description = "Experimentals get unique icons by their category - from BrewLAN."
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_Plenae/ExperimentalIcons/Experimental-Icon-Overhaul_Mod_Icon.dds"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
