--*****************************************************************************
--* File: lua/modules/ui/lobby/ainames.lua
--* Author: Chris Blackwell
--* Summary: Contains a list of names the AI can assign to units
--*
--* Copyright © 2006 Gas Powered Games, Inc.  All rights reserved.
--*****************************************************************************

ainames = {

    uef = {
        "Dewster",
        "Keville",
        "Janicki",
        "Jesus Chrysler",
        "Staltman",
        "Kirwan",
        "Defwode",
        "RD Maxon",
        "Cox",
        "Budac",
        "Garat",
        "Rumsey",
        "Scolar",
        "Smolko",
        "DeMelt",
        "Gecko Mucousface",
        "Murdock",
        "Xavier",
        "Mavor",
        "Vasudevan",
        "Vidhee",
        "Dimmick",
        "Zimm",
        "Kohne",
        "Frostberry",
    },
    aeon = {
        "Goober",
        "Ironhand",
        "Azraelian",
        "Xavier 4 Eyes",
        "Tanksy",
        "Svend Ziderzee",
        "Zoe",
        "Jessica",
        "Ivan",
        "Maegan",
        "Simone",
        "Albarel",
        "Daroza",
        "Logan",
        "Yare",
        "Lanette",
        "Sletir",
        "Motoko",
        "Bassima",
        "The Balthazar",
        "Janus",
        "Ocarina",
        "Kayleen",
        "Lish",
        "Mazpar",
    },
    cybran = {
        "Sprouto",
        "Loudolo",
        "BatGecko",
        "Snooker",
        "CR07-A",
        "M4h0n",
        "Kraglor",
        "LOUDNESS",
        "DFS",
        "Winter Knight",
        "Spyder",
        "Daedalus",
        "Squid",
        "Kijanka",
        "Phoenix",
        "Yo-Yo",
        "Xahvres",
        "XShadowStormX",
        "Cracker",
        "Blacklisted",
        "Avatar",
        "5Iron",
        "TheContact",
        "Red Collective",
        "Jackal",
        "C@tch22",
        "Rokion Era",
        "Unfather",
        "TargetDrone",
        "GStar",
        "Sckricko",
    },
    seraphim = { 
        "Terhminate-Or",
        "Stash-Ullevash",
        "Ahn-Aishayeth",
        "Ahn-Iashen",
        "Stash-Ushithow",
        "Shun-Awloyeth",
        "Stash-Ushi",
        "Shun-Ylliushi",
        "Shun-Eoshi",
        "Zan-Iavow",
        "Zan-Ilnaa",
        "Zan-Uyalthow",
        "Zan-Uushen",
        "Oum-Ullehesh",
        "Oum-Ayla",
        "Oum-Ashavoh",
        "Oum-Zala",
        "Thel-Aishashen",
        "Thel-Awloshi",
        "Thel-Ylliuhesh",
        "Thel-Ilthow",
        "Seth-Eovash",
        "Seth-Uu",
        "Seth-Ushavoh",
        "Seth-Uthivow",
        "Paj-Tshiab",
        "Al-Ghoussein",
    },
    
}
