name = "Enhanced Resources"
version = 1.08
copyright = "Copyright © 2006, Gas Powered Games"
description = "Increases resource production by 15%, and decreases unit cost & build time by 10%."
author = "Gas Powered Games"
url = "http://www.gaspoweredgames.com"
uid = "74A9EAB2-E851-11DB-A1F1-F2C755D89593"
exclusive = false
ui_only = false
