Description = {
--UEF UNITS
	--Commanders  
	['uel0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch.",
	['uel0001-tm'] = "Mounts a tactical cruise missile launcher onto the back of the ACU.",
	['uel0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.",
	['uel0001-dsu'] = "Greatly increases the speed at which the ACU repairs itself.",
	['uel0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.",
	['uel0001-hamc'] = "Increases main cannon's damage output by several factors. Also increases range of main cannon and Overcharge.",
	['uel0001-srtn'] = "Adds a short-range tactical nuke.",
	['uel0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.",
	['uel0001-sgf'] = "Expands the radius of the ACU's personal shield. Requires Energy to run.",
	['uel0001-isb'] = "Increases ACU's resource generation.",
	['uel0001-psg'] = "Creates a protective shield around the ACU. Requires Energy to run.",
	['uel0001-led'] = "Engineering Drone acts as a secondary Engineer. Assists the ACU where applicable.",
	['uel0001-red'] = "Adds a second Engineering Drone. Requires an initial Engineering Drone.",

	--Support Commanders 
	['uel0301'] = "A multi-purpose construction, repair, capture and reclamation unit with superior build power and access to Experimental blueprints. ",
	['uel0301-ed'] = "Engineering Drone acts as a secondary Engineer. Assists the SACU where applicable.",
	['uel0301-psg'] = "Creates a protective shield around the SACU. Requires Energy to run.",
	['uel0301-sgf'] = "Expands the radius of the SACU's personal shield. Requires Energy to run.",
	['uel0301-rj'] = "Radar Jammer creates false radar images. Countered by Omni sensors.",
	['uel0301-isb'] = "Increases SACU's resource generation.",
	['uel0301-sre'] = "Greatly expands the range of the standard onboard SACU sensor systems.",
	['uel0301-acu'] = "Rapidly cools any weapon mounted onto the SACU. Increases rate of fire.",
	['uel0301-heo'] = "Equips the standard SACU Heavy plasma cannon with area-of-effect damage.",

	--Land
	['uel0101'] = "Fast, lightly armored reconnaissance vehicle. Armed with a machine gun and a state-of-the-art sensor suite.",
	['uel0106'] = "Lightly armored mech. Provides direct-fire support against low-end units.",
	['uel0103'] = "Versatile mobile artillery unit. Designed to engage enemy units at long range.",
	['uel0104'] = "Mobile anti-air defense. Effective against low-end enemy air units.",
	['uel0201'] = "Lightly armored tank. Armed with a single cannon.",
	['uel0202'] = "Heavy tank. Equipped with reinforced armor and dual cannons.",
	['uel0203'] = "Amphibious tank. Provides direct-fire support with two riot guns.", 
	['uel0111'] = "Heavily armored, mobile tactical missile launcher. Designed to attack at long range.",
	['uel0205'] = "Mobile AA unit. Armed with flak artillery.",
	['uel0307'] = "Mobile shield generator.",
	['uel0303'] = "Shielded heavy assault bot. Armed with two cannons and tactical rocket launcher.",
	['uel0304'] = "Slow-moving heavy artillery. Must be stationary to fire.",
	['uel0401'] = "Experimental, amphibious mobile factory. Equipped with battleship-level weapons and armor. Its shield consumes Energy.",
	['xel0305'] = "Slow-moving, heavily armored assault bot. Designed to engage base defenses and structures.",
	['xel0306'] = "Mobile missile launcher. Long reload time. Designed to overwhelm enemy shields and tactical missile defenses with large salvos.",

	--AIR
	['uea0101'] = "Standard air scout.",
	['uea0102'] = "Quick, maneuverable fighter. Armed with linked AA railguns.",
	['uea0103'] = "Lightly armored area-of-effect bomber.",
	['uea0107'] = "Low-end air transport. Can carry up to 6 units.",
	['uea0203'] = "Light gunship. Equipped with one riot gun and a single transportation clamp.",
	['uea0204'] = "Torpedo bomber. Armed with a payload of Angler torpedoes.",
	['uea0302'] = "Extremely fast spy plane. Equipped with mid-level surveillance equipment.",
	['uea0104'] = "Armed, mid-level air transport. Equipped with riot guns and AA weapons. Can carry up to 12 units.",
	['uea0303'] = "High-end air fighter. Designed to engage air units of any type.",
	['uea0304'] = "High-end strategic bomber. Armed with a small yield nuclear bomb and light AA gun.",
	['uea0305'] = "Heavy gunship. Armed with two tactical rocket launchers and an AA railgun.", 
	['xea0306'] = "Heavy air transport. Features 28 transportation clamps, heavy cannons, missile launchers and a shield generator. Can carry up to 28 units.",

	--SEA
	['ues0103'] = "Naval support unit. Equipped with a single cannon, AA railgun, radar, sonar and radar jammer.",
	['ues0203'] = "Low-end attack submarine.",
	['ues0202'] = "Anti-aircraft naval vessel. Armed with AA missile system, SAM system and tactical missile launcher.", 
	['ues0201'] = "Mid-level naval unit. Equipped with a torpedo bay, anti-torpedo defense, dual cannons and a single AA weapon.",
	['ues0302'] = "Shore bombardment and anti-ship vessel. Armed with three heavy cannons, four AA railguns and two anti-missile guns.",
	['ues0304'] = "Strategic missile submarine. Armed with long-range tactical missiles and a strategic missile launcher.",
	['ues0401'] = "Submersible aircraft carrier. Can store, transport and repair aircraft. Armed with torpedo launchers and AA weapons.",
	['xes0102'] = "Dedicated sub-killer. Armed with a torpedo tube and anti-torpedo charges.",
	['xes0205'] = "Naval shield generator. Provides protection for all nearby vessels.",
	['xes0307'] = "High-end anti-naval vessel. Armed with plasma beams, torpedo systems, anti-missile defenses and anti-torpedo charges.",

	--Buildings 
	['ueb2101'] = "Low-end defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['ueb2104'] = "Anti-air tower. Designed to engage low-end aircraft.",
	['ueb2109'] = "Anti-naval defense system.",
	['ueb5101'] = "Restricts the movement of enemy units. Offers minimal protection from enemy fire.",
	['ueb2301'] = "Heavily armored defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['ueb2204'] = "Anti-air tower. Designed to engage mid-level aircraft.",
	['ueb4201'] = "Tactical missile defense. Protection is limited to the structure's operational area.",
	['ueb2205'] = "Anti-naval defense system. Designed to engage all naval units.",
	['ueb4202'] = "Generates a protective shield around units and structures within its radius.",

	['ueb2304'] = "High-end anti-air tower. Designed to engage all levels of aircraft.",
	['ueb4302'] = "Strategic missile defense. Protection is limited to the structure's operational area.",
	['ueb4301'] = "Generates a heavy shield around units and structures within its radius.",
	['ueb2303'] = "Stationary artillery. Designed to engage slow-moving units and fixed structures.",
	['ueb2108'] = "Tactical missile launcher. Must be ordered to construct missiles.",
	['ueb5202'] = "Refuels and repairs aircraft. Air patrols will automatically use facility.",
	['ueb2302'] = "Stationary heavy artillery with excellent range, accuracy and damage potential. ",
	['ueb2305'] = "Strategic missile launcher. Constructing missiles costs resources. Must be ordered to construct missiles.",
	['ueb0304'] = "Summons Support Commander(s).",
	['ueb2401'] = "Extremely advanced strategic artillery. Unlimited range, pin-point accuracy and devastating ordinance.",
	['xeb2306'] = "Heavy defensive tower. Attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['xeb2402'] = "Satellite-based weapon system. Attacks enemy units and structures. If its control center is destroyed, the weapon is immediately disabled.",

	--Engineers
	['uel0105'] = "Tech 1 amphibious construction, repair, capture and reclamation unit.",
	['uel0208'] = "Tech 2 amphibious construction, repair, capture and reclamation unit.",
	['uel0309'] = "Tech 3 amphibious construction, repair, capture and reclamation unit.",
	['xel0209'] = "Tech 2 amphibious construction, repair, capture and reclamation unit. Armed with a Riot Gun and internal radar and jammer.",
	['xeb0104'] = "Automatically repairs, reclaims, assists or captures any unit within its operational radius.",   
	['xeb0204'] = "Automatically repairs, reclaims, assists or captures any unit within its operational radius.",

	--Factories
	['ueb0101'] = "Constructs Tech 1 land units. Upgradeable.",
	['ueb0102'] = "Constructs Tech 1 air units. Upgradeable.",
	['ueb0103'] = "Constructs Tech 1 naval units. Upgradeable.",
	['ueb0201'] = "Constructs Tech 2 land units. Upgradeable.",
	['ueb0202'] = "Constructs Tech 2 air units. Upgradeable.",
	['ueb0203'] = "Constructs Tech 2 naval units. Upgradeable.",
	['ueb0301'] = "Constructs Tech 3 land units. Highest tech level available.",
	['ueb0302'] = "Constructs Tech 3 air units. Highest tech level available.",
	['ueb0303'] = "Constructs Tech 3 naval units. Highest tech level available.",

	--Buildings
	['ueb1101'] = "Generates Energy. Construct next to other structures for adjacency bonus.",
	['ueb1102'] = "Generates Energy. Must be constructed on hydrocarbon deposits. Construct structures next to Hydrocarbon power plant for adjacency bonus.",
	['ueb1105'] = "Stores Energy. Construct next to power generators for adjacency bonus or next to shields for enhanced shield performance.",
	['ueb1103'] = "Extracts Mass. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['ueb1104'] = "Creates Mass. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",
	['ueb1106'] = "Stores Mass. Construct next to extractors or fabricators for enhanced mass output.",
	['ueb1201'] = "Mid-level power generator. Construct next to other structures for adjacency bonus.",
	['ueb1202'] = "Mid-level Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['ueb1301'] = "High-end power generator. Construct next to other structures for adjacency bonus.",
	['ueb1302'] = "High-end Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['ueb1303'] = "High-end Mass fabricator. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",
	['ueb3101'] = "Radar system with minimal range. Detects and tracks surface and air units.",
	['ueb3102'] = "Sonar system with minimal range. Detects and tracks naval units.",
	['ueb3201'] = "Radar system with moderate range. Detects and tracks surface and air units.",
	['ueb3202'] = "Sonar system with moderate range. Detects and tracks naval units.",
	['ueb4203'] = "Generates stealth field. Hides units and structures from radar detection within its operational range. Countered by optical and Omni sensors.",
	['ues0305'] = "Sonar system with exceptional range. Detects and tracks naval units. Armed with a bottom-mounted torpedo turret.",
	['ueb3104'] = "High-end intelligence system. Provides maximum radar and sonar coverage. Counters enemy intelligence systems.",

--CYBRAN UNITS
	--Commanders
	['url0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch.",   
	['url0001-ras'] = "Increases ACU's resource generation.",
	['url0001-pcg'] = "Cloaks the ACU from optical sensors and increases maximum health. Can be detected by Omni Sensors. Requires Energy to run.",
	['url0001-psg'] = "Hides the ACU from radar. Requires Energy to run.",
	['url0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.",
	['url0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.",
	['url0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.",
	['url0001-acu'] = "Increases main cannon's rate of fire and range. Also increases range of the Molecular Ripper and Overcharge.",
	['url0001-mlg'] = "ACU can generate a beam laser that sweeps over enemy units.",
	['url0001-ntt'] = "Equips the ACU with a standard Cybran Nanite torpedo tube and sonar.",

    --Support Commanders 
	['url0301'] = "A multi-purpose construction, repair, capture and reclamation unit with superior build power and access to Experimental blueprints. ",
	['url0301-cfs'] = "Cloaks the SACU from optical sensors. Can be detected by Omni Sensors. Requires Energy to run.",
	['url0301-emp'] = "EMP burst effectively disables enemy units for a few seconds.",
	['url0301-fc'] = "Greatly enhances the pulse laser's cohesion, almost doubling its damage output.",
	['url0301-nms'] = "Adds AA defensive system.",
	['url0301-ras'] = "Increases SACU's resource generation.",
	['url0301-ses'] = "Speeds up all engineering-related functions.",
	['url0301-srs'] = "Greatly increases the speed at which the SACU repairs itself.",
	['url0301-sfs'] = "Hides the SACU from radar. Requires Energy to run.",

	--Land units
	['url0101'] = "Fast, lightly armored reconnaissance vehicle. Equipped with a cloaking field.",
	['url0106'] = "Lightly armored strike bot. Provides direct-fire support against low-end units.",
	['url0107'] = "Assault bot. Equipped with two heavy laser autoguns and can self-repair itself.", 
	['url0103'] = "Versatile mobile artillery unit. Designed to engage enemy units at long range and disable them with an EMP blast.",
	['url0104'] = "Primary function is anti-air defense. Can be configured to attack land units.",
	['url0202'] = "Heavy tank. Armed with two cannons.",
	['url0203'] = "Submersible, amphibious tank. Armed with a heavy bolter and torpedo launcher.",
	['url0111'] = "Mobile missile launcher. Designed to attack at long range.",
	['url0205'] = "Mobile AA unit. Armed with flak artillery.",
	['url0306'] = "Mobile stealth generator.",
	['url0303'] = "Siege assault bot. Armed with a Disintegrator Pulse laser and heavy bolter.",
	['url0304'] = "Slow-moving heavy artillery. Must be stationary to fire.",
	['url0402'] = "Experimental bot. Consumes massive amounts of Energy. Its main laser sweeps across any enemy to its front. Also armed with AA defenses.",
	['url0401'] = "Experimental, rapid-fire artillery. Consumes massive amounts of Energy with each shot. Must be stationary to fire. ",
	['xrl0302'] = "Mobile bomb. Must be moved into position and manually detonated.",
	['xrl0305'] = "Amphibious assault bot. Capable of attacking land and naval units.",
	['xrl0403'] = "Massive experimental bot. Equipped with Dual-Proton cannons, AA defenses, torpedo launchers and anti-torpedo flares. Drops 'eggs' that can be transformed into a single unit.",

	--Crab Egg Units
	['xrl0002'] = "Tech 3 amphibious construction, repair, capture and reclamation unit.",
	['xrl0003'] = "Amphibious assault bot. Capable of attacking land and naval units.",
	['xrl0004'] = "Mobile AA unit. Armed with flak artillery.",
	['xrl0005'] = "Slow-moving heavy artillery. Must be stationary to fire.",

	--Air units
	['ura0101'] = "Standard air scout.",
	['ura0102'] = "Quick, maneuverable fighter. Armed with an auto-cannon.",
	['ura0103'] = "Lightly armored area-of-effect bomber.",
	['ura0107'] = "Low-end air transport. Can carry up to 6 units.",
	['ura0203'] = "Fast-attack copter. Armed with twin rocket tubes.",
	['ura0204'] = "Mid-level torpedo bomber.",
	['ura0302'] = "Extremely fast spy plane with free, permanent stealth.",
	['ura0104'] = "Mid-level air transport. Armed with an auto-cannon and AA defense system. Can carry up to 10 units.",
	['ura0303'] = "High-end air fighter. Designed to engage air units of any type.",
	['ura0304'] = "High-end strategic bomber. Armed with a Proton bomb, stealth field generator and AA flak cannon.",
	['ura0401'] = "Experimental gunship. Delivers extreme firepower via rocket racks, electron bolters and missile system.",
	['xra0105'] = "Light gunship. Primary role is base defense. Effective against low-level ground units.",
	['xra0305'] = "Heavy gunship armed with Nanite missiles, Disintegration Pulse lasers and a radar jamming suite. Offers direct fire support.",

	--Naval Units
	['urs0103'] = "Naval radar and sonar platform. Armed with a Proton cannon and an AA auto-cannon.",
	['urs0203'] = "Attack submarine. Armed with a Nanite torpedo launcher and a deck-mounted heavy laser.",
	['urs0202'] = "Anti-air naval vessel. Equipped with AA turrets and short-range rocket platform.",
	['urs0201'] = "Amphibious destroyer. Armed with a single Dual-Proton cannon, AA auto-cannon and torpedo tubes.",
	['urs0302'] = "Direct fire and bombardment naval vessel. Armed with six Proton cannons, dual AA auto-cannons, anti-missile turrets and torpedo tubes.",
	['urs0303'] = "Aircraft carrier. Can store, transport and repair aircraft. Armed with light AA auto-cannons and an anti-missile turret.",
	['urs0304'] = "Strategic missile submarine. Armed with a strategic missile launcher, tactical missile launcher and torpedo tubes.",
	['xrs0204'] = "Mid-level anti-naval unit. Equipped with mobile sonar stealth. Effective against surface vessels and submerged units.", 
	['xrs0205'] = "Unarmed counter-intelligence vessel. Equipped with stealth field that counters enemy sonar and radar.",
	['urb2101'] = "Low-end defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['urb2104'] = "Anti-air tower. Designed to engage low-end aircraft.",
	['urb2109'] = "Anti-naval defense system.",
	['urb5101'] = "Restricts the movement of enemy units. Offers minimal protection from enemy fire.",
	['urb2301'] = "Heavily armored defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['urb2204'] = "Anti-air tower. Designed to engage mid-level aircraft.",
	['urb4201'] = "Tactical missile defense. Protection is limited to the structure's operational area.",
	['urb2205'] = "Anti-naval defense system. Designed to engage all naval units.",
	['urb4202'] = "Generates a protective shield around units and structures within its radius. Shield can be upgraded four times.",
	['urb4202-ch'] = "Upgrade increases shield's size, strength and operating costs.",
	['xrb0104'] = "Automatically repairs, reclaims, assists or captures any unit within its operational radius.",
	['xrb0204'] = "Automatically repairs, reclaims, assists or captures any unit within its operational radius.",
	['xrb0304'] = "Automatically repairs, reclaims, assists or captures any unit within its operational radius.",
	['xrb2308'] = "Submerged torpedo launcher. Capable of destroying the largest of enemy vessels.",
	['xrb3301'] = "Offers complete line-of-sight within its operational area.",
	['urb2304'] = "High-end anti-air tower. Designed to engage all levels of aircraft.",
	['urb4302'] = "Strategic missile defense. Protection is limited to the structure's operational area.",
	['urb2303'] = "Heavy artillery. Designed to engage slow-moving units and fixed structures.",
	['urb2108'] = "Tactical missile launcher. Must be ordered to construct missiles.",
	['urb5202'] = "Refuels and repairs aircraft. Air patrols will automatically use facility.",
	['urb2302'] = "Heavy artillery with excellent range, accuracy and damage potential.",
	['urb2305'] = "Strategic missile launcher. Constructing missiles costs resources. Must be ordered to construct missiles.",
	['urb0304'] = "Summons Support Commander(s).",

	--Engineers
	['url0105'] = "Tech 1 amphibious construction, repair, capture and reclamation unit.",
	['url0208'] = "Tech 2 amphibious construction, repair, capture and reclamation unit.",
	['url0309'] = "Tech 3 amphibious construction, repair, capture and reclamation unit.",

	--Factories etc
	['urb0101'] = "Constructs Tech 1 land units. Upgradeable.",
	['urb0102'] = "Constructs Tech 1 air units. Upgradeable.",
	['urb0103'] = "Constructs Tech 1 naval units. Upgradeable.",
	['urb0201'] = "Constructs Tech 2 land units. Upgradeable.",
	['urb0202'] = "Constructs Tech 2 air units. Upgradeable.",
	['urb0203'] = "Constructs Tech 2 naval units. Upgradeable.",
	['urb0301'] = "Constructs Tech 3 land units. Highest tech level available.",
	['urb0302'] = "Constructs Tech 3 air units. Highest tech level available.",
	['urb0303'] = "Constructs Tech 3 naval units. Highest tech level available.",

	--Base stuff
	['urb1101'] = "Generates Energy. Construct next to other structures for adjacency bonus.",
	['urb1102'] = "Generates Energy. Must be constructed on hydrocarbon deposits. Construct structures next to Hydrocarbon power plant for adjacency bonus.",
	['urb1103'] = "Extracts Mass. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['urb1104'] = "Creates Mass. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",
	['urb1106'] = "Stores Mass. Construct next to extractors or fabricators for adjacency bonus.",
	['urb1105'] = "Stores Energy. Construct next to power generators for enhanced output or next to shields for enhanced shield peformance.",
	['urb1201'] = "Mid-level power generator. Construct next to other structures for adjacency bonus.",
	['urb1202'] = "Mid-level Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['urb1301'] = "High-end power generator. Construct next to other structures for adjacency bonus.",
	['urb1302'] = "High-end Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['urb1303'] = "High-end Mass fabricator. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",
	['urb3101'] = "Radar system with minimal range. Detects and tracks surface and air units.",
	['urb3102'] = "Sonar system with minimal range. Detects and tracks naval units.",
	['urb3201'] = "Radar system with moderate range. Detects and tracks surface and air units.",
	['urb3202'] = "Sonar system with moderate range. Detects and tracks naval units.",
	['urb4203'] = "Generates stealth field. Hides units and structures within its operational range. Countered by optical and Omni sensors.",
	['urs0305'] = "Sonar system with exceptional range. Detects and tracks naval units. Equipped with a stealth field generator.",
	['urb3104'] = "High-end intelligence system. Provides maximum radar and sonar coverage. Counters enemy intelligence systems.",

--AEON UNITS
	--Commanders  
	['ual0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch.",
	['ual0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.",
	['ual0001-cd'] = "Creates a Quantum Stasis Field around the ACU. Immobilizes enemy units within its radius. High Energy Consumption.",
	['ual0001-cba'] = "Enhances the ACU's Quantum Disrupter beam. Nearly doubles its range.",
	['ual0001-ess'] = "Greatly expands the range of the standard onboard ACU sensor systems.",
	['ual0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.",
	['ual0001-hsa'] = "Rapidly cools the Quantum Disruptor beam. Increases rate of fire.",
	['ual0001-ras'] = "Increases ACU's resource generation.",
	['ual0001-eras'] = "Requires Resource Allocation System. Further increases ACU's resource generation.",
	['ual0001-ptsg'] = "Creates a protective shield around the ACU. Requires Energy to run.",
	['ual0001-phtsg'] = "Enhances the protective shield around the ACU. Requires Energy to run.",
	['ual0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.",

	-- Support Commanders 
	['ual0301'] = "A multi-purpose construction, repair, capture and reclamation unit with superior build power and access to Experimental blueprints. ",
	['ual0301-efm'] = "Speeds up all engineering-related functions.",
	['ual0301-ras'] = "Increases SACU's resource generation.",
	['ual0301-sp'] = "SACU is sacrificed and its Mass is added to a structure. This destroys the SACU.",
	['ual0301-tsg'] = "Creates a protective shield around the SACU.",
	['ual0301-htsg'] = "Upgrades the SACU's protective shield. Requires Energy to run.",
	['ual0301-ss'] = "Equips the standard SACU's Reacton cannon with area-of-effect damage.",
	['ual0301-sic'] = "Greatly increases the speed at which the SACU repairs itself.",
	['ual0301-pqt'] = "Adds teleporter. Requires considerable Energy to activate.",

	--Land
	['ual0101'] = "Fast, lightly armored reconnaissance vehicle. Armed with a laser and a state-of-the-art sensor suite.",
	['ual0106'] = "Fast, lightly armored assault bot. Fires a short-range sonic weapon.",
	['ual0201'] = "Amphibious light tank. Armed with a single cannon.",
	['ual0103'] = "Mobile light artillery. Designed to engage enemy units at long range.",
	['ual0104'] = "Mobile anti-air unit. Effective against low-end enemy air units.",
	['ual0202'] = "Heavy tank. Equipped with a single cannon and a shield generator.",
	['ual0111'] = "Mobile tactical missile launcher. Missile has medium range and inflicts light damage.",
	['ual0205'] = "Mobile AA unit. Armed with a temporal AA Fizz launcher.",
	['ual0307'] = "Mobile shield generator.",
	['ual0303'] = "Shielded Siege assault bot. Armed with a high-intensity laser. Can repair and reclaim Mass.",
	['ual0304'] = "Slow-moving heavy artillery. Must be stationary to fire.",
	['ual0401'] = "Sacred assault bot. Incinerates enemy units and structures with Phason laser. Also equipped with tractor beam. Pulls in and crushes mobile enemy units.",
	['xal0203'] = "Fast, lightly armored tank. Armed with dual, rapid-fire autoguns.",
	['xal0305'] = "Fast-moving sniper bot. Designed to strike high-value targets from a distance.", 

	--Air
	['uaa0101'] = "Standard air scout.",
	['uaa0102'] = "Quick, maneuverable fighter. Armed with sonic pulse battery.",
	['uaa0103'] = "Lightly armored bomber. Armed with a Chrono bomb that destroys and disables targeted units.",
	['uaa0107'] = "Low-end air transport. Can carry up to 6 units.",
	['uaa0203'] = "Armored gunship. Quad-barreled light laser mounted on its underside.",
	['uaa0204'] = "Torpedo bomber. Armed a payload of Harmonic depth charges.",
	['uaa0302'] = "Extremely fast spy plane. Equipped with mid-level radar system.",
	['uaa0104'] = "Mid-level air transport. Armed with sonic pulse batteries. Can carry up to 12 units.",
	['uaa0303'] = "High-end air fighter. Designed to engage air units of any type.",
	['uaa0304'] = "High-end strategic bomber. Armed with a Quark bomb and decoy flares.",
	['uaa0310'] = "Flying fortress. Armed with Quantum beam generator, AA systems and depth charges. Can store, transport and repair aircraft.",
	['xaa0202'] = "Mid-level air fighter.  Excellent AA capabilities. Effective against enemy gunships and bombers.",
	['xaa0305'] = "Heavily armored gunship. Armed with quad-light laser and Zealot missiles.",
	['xaa0306'] = "Torpedo bomber. Designed to engage high-level naval units.",

	--Naval
	['uas0103'] = "Naval support unit. Equipped with a radar, sonar and anti-torpedo charges.",
	['uas0203'] = "Low-end attack submarine.",
	['uas0102'] = "Anti-aircraft naval vessel. Armed with AA sonic pulse battery.",
	['uas0202'] = "Mid-level anti-aircraft naval vessel. Armed with two AA missile launchers, dual-barreled Quantum cannon and tactical missile flares.", 
	['uas0201'] = "Sub-killer. Equipped with an Oblivion cannon, torpedo tubes, Harmonic depth charges and anti-torpedo charges.",
	['uas0302'] = "High-end anti-naval vessel. Equipped with three Oblivion cannons and anti-missile flares.",
	['uas0303'] = "Aircraft carrier. Can store, transport and repair aircraft. Armed with surface-to-air missile launchers.",
	['uas0304'] = "Strategic missile submarine. Armed with Serpentine tactical missiles and a strategic missile launcher.",
	['uas0401'] = "Submersible battleship. Armed with heavy torpedo launchers and a single Oblivion cannon. Can construct light support naval units.",
	['xas0204'] = "Submerged anti-naval unit. Effective against both surface vessels and submerged units.",
	['xas0306'] = "High-end missile ship. Armed with two racks of highly accurate Serpentine tactical missiles.",

	--Buildings
	['uab2101'] = "Low-end defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['uab2104'] = "Anti-air tower. Designed to engage low-end aircraft.",
	['uab2109'] = "Anti-naval defense system.",
	['uab5101'] = "Restricts the movement of enemy units. Offers minimal protection from enemy fire.",
	['uab2301'] = "Heavily armored defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['uab2204'] = "Anti-air tower. Designed to engage mid-level aircraft.",
	['uab4201'] = "Tactical missile defense. Protection is limited to the structure's operational area.",
	['uab2205'] = "Heavy anti-naval defense system. Designed to engage all naval units.",
	['uab4202'] = "Generates a protective shield around units and structures within its radius.",
	['uab2304'] = "High-end anti-air tower. Designed to engage all levels of aircraft.",
	['uab4302'] = "Strategic missile defense. Protection is limited to the structure's operational area.",
	['uab4301'] = "Generates a protective shield around units and structures within its radius.",
	['uab2303'] = "Mid-level artillery. Designed to engage slow-moving units and fixed structures.",
	['uab2108'] = "Tactical missile launcher. Must be ordered to construct missiles.",
	['uab5202'] = "Refuels and repairs aircraft. Air patrols will automatically use facility.",
	['uab2302'] = "Heavy artillery with excellent range, accuracy and damage potential. ",
	['uab2305'] = "Strategic missile launcher. Constructing missiles costs resources. Must be ordered to construct missiles.",
	['uab0304'] = "Summons Support Commander(s).",
	['xab2307'] = "Rapid-fire artillery system. Provides indirect fire support. Ordinance inflicts light damage across a large area.",
	['xab3301'] = "Offers line-of-sight to a fixed location on the battlefield.",

   
   --Engineers
	['ual0105'] = "Tech 1 amphibious construction, repair, capture and reclamation unit.",
	['ual0208'] = "Tech 2 amphibious construction, repair, capture and reclamation unit.",
	['ual0309'] = "Tech 3 amphibious construction, repair, capture and reclamation unit.",

	['uab0101'] = "Constructs Tech 1 land units. Upgradeable.",
	['uab0102'] = "Constructs Tech 1 air units. Upgradeable.",
	['uab0103'] = "Constructs Tech 1 naval units. Upgradeable.",
	['uab0201'] = "Constructs Tech 2 land units. Upgradeable.",
	['uab0202'] = "Constructs Tech 2 air units. Upgradeable.",
	['uab0203'] = "Constructs Tech 2 naval units. Upgradeable.",
	['uab0301'] = "Constructs Tech 3 land units. Highest tech level available.",
	['uab0302'] = "Constructs Tech 3 air units. Highest tech level available.",
	['uab0303'] = "Constructs Tech 3 naval units. Highest tech level available.",
	['uab1101'] = "Generates Energy. Construct next to other structures for adjacency bonus.",
	['uab1102'] = "Generates Energy. Must be constructed on hydrocarbon deposits. Construct structures next to Hydrocarbon power plant for adjacency bonus.",
	['uab1105'] = "Stores Energy. Construct next to power generators for enhanced power output or next to shields for enhanced shield performance.",
	['uab1103'] = "Extracts Mass. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['uab1104'] = "Creates Mass. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",
	['uab1106'] = "Stores Mass. Construct next to extractors or fabricators for adjacency bonus.",
	['uab1201'] = "Mid-level power generator. Construct next to other structures for adjacency bonus.",
	['uab1202'] = "Mid-level Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['uab1301'] = "High-end power generator. Construct next to other structures for adjacency bonus.",
	['uab1302'] = "High-end Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['uab1303'] = "High-end Mass fabricator. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",
	['uab3101'] = "Radar system with minimal range. Detects and tracks surface and air units.",
	['uab3102'] = "Sonar system with minimal range. Detects and tracks naval units.", 
	['uab3201'] = "Radar system with moderate range. Detects and tracks surface and air units.",
	['uab3202'] = "Sonar system with moderate range. Detects and tracks naval units.",
	['uab4203'] = "Generates stealth field. Hides units and structures within its operational range. Countered by optical and Omni sensors.",
	['uas0305'] = "Sonar system with exceptional range. Detects and tracks naval units. Equipped with anti-torpedo launchers.",
	['uab3104'] = "High-end intelligence system. Provides maximum radar and sonar coverage. Counters enemy intelligence systems.", 
	['xab1401'] = "The peak of mass and energy generation, it draws resources directly from the crust of the planet.  Roughly equal to 10 Mass Fabs and Fusion power plants, this building is highly volatile.  Output will decrease if too many are constructed in any given map area.",

--SERAPHIM UNITS
	--Seraphim Commanders
	['xsl0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch.",
	['xsl0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.",
    ['xsl0001-dss'] = "Increases the speed at which the ACU repairs itself. Also increases hit points.",
	['xsl0001-adss'] = "Further increases the speed at which the ACU repairs itself. Also increases hitpoints.",
	['xsl0001-ras'] = "Increases ACU's resource generation.",
	['xsl0001-eras'] = "Requires Resource Allocation System. Further increases ACU's resource generation.",
	['xsl0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.",
	['xsl0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.",
	['xsl0001-cba'] = "Increases the damage inflicted by ACU's primary weapon. Adds area-of-effect damage.",
	['xsl0001-nrf'] = "Automatically speeds up the repair speed of nearby units.",
    ['xsl0001-anrf'] = "Further speeds up the repair speed of nearby units. Increases maximum health of nearby units.",
	['xsl0001-hsa'] = "Increases main cannon's rate of fire and range. Also increases range of Overcharge.",
	['xsl0001-tml'] = "Mounts a tactical cruise missile launcher onto the back of the ACU.",
	
	['xsl0301'] = "A multi-purpose construction, repair, capture and reclamation unit with superior build power and access to Experimental blueprints. ",
    ['xsl0301-tmu'] = "Mounts a tactical cruise missile launcher onto the back of the SACU.",
    ['xsl0301-dss'] = "Increases the speed at which the SACU repairs itself. Also increases hit points.",
	['xsl0301-sre'] = "Greatly expands the range of the standard onboard SACU sensor systems, including Omni.",
	['xsl0301-efm'] = "Speeds up all engineering-related functions.",
	['xsl0301-sp'] = "Adds a personal shield generator to the SACU.",
    ['xsl0301-pqt'] = "Adds teleporter. Requires considerable Energy to activate.",
	['xsl0301-oc'] = "Single shot destroys most units. Consumes large amount of Energy.",

	--Land Units
	['xsl0101'] = "Light, fast mobile reconnaissance unit. When stationary, deploys cloaking and stealth fields.",
	['xsl0201'] = "Lightly armored tank. Armed with a single cannon.",
	['xsl0103'] = "Amphibious mobile light artillery. Provides indirect fire support.",
	['xsl0104'] = "Mobile anti-air defense. Effective against low-end enemy air units.",
	['xsl0202'] = "Lightly armored assault bot. Effective against equivalent enemy units.",
	['xsl0203'] = "Amphibious tank. Armed with a single cannon.",
	['xsl0111'] = "Relatively fast-moving mobile tactical missile launcher.",
	['xsl0205'] = "Mobile AA unit that uses flak artillery.",
	['xsl0303'] = "Amphibious siege tank that is armed with a slow-firing Thau cannon. Also armed with bolters and a single torpedo launcher.",
	['xsl0305'] = "Lightly armored, fast sniper bot. Armed with an extremely powerful energy rifle.",
	['xsl0304'] = "Mobile heavy artillery. Ordinance inflicts moderate damage upon impact.",
	['xsl0307'] = "High-end mobile shield generator.",
	['xsl0401'] = "A two-stage weapon. In its initial form, it fires an extremely destructive Phason laser. When the primary unit is destroyed, it unleashes a ferocious Quantum energy being.",

	--Air Units
	['xsa0101'] = "Standard air scout",
	['xsa0102'] = "Quick, agile air fighter. Armed with a Gatling-style weapon.",
	['xsa0103'] = "Fast-moving tactical bomber. Lightly armored.",
	['xsa0107'] = "Low-end air transport. Can carry up to 8 units.",
	['xsa0202'] = "Combined fighter/bomber. Armed with two AA weapons and a tactical bomb.",
	['xsa0203'] = "Heavily armored gunship. Armed with four heavy Phasic autoguns.",
	['xsa0204'] = "Torpedo bomber. Fires three heavy Cavitation torpedoes at its target.",
	['xsa0104'] = "Mid-level air transport. Can carry up to 16 units.",
	['xsa0302'] = "Fast, agile spy plane. Equipped with on-board radar and sonar.",
	['xsa0303'] = "High-end air fighter. Designed to engage air units of any type.",
	['xsa0304'] = "High-end strategic bomber. Inflicts excellent single target and area-of-effect damage.",
	['xsa0402'] = "Massive bomber capable of devastating entire bases. Armed with an experimental strategic bomb and three AA auto-cannons.",

	--Naval Units
	['xss0103'] = "Low-end naval unit. Armed with an auto-cannon and AA Gatling gun.",
	['xss0203'] = "Low-end attack submarine.",
	['xss0202'] = "Mid-level naval unit. Equipped with AA artillery cannons, tactical missile launcher and tactical missile defense.",
	['xss0201'] = "Dedicated sub-killer. Equipped with a torpedo launcher, anti-vessel beam weapons and torpedo defense.",
	['xss0302'] = "High-end naval vessel. Armed with three heavy Quarnon cannons, two AA cannons, two tactical missile defenses and a strategic missile launcher.",
	['xss0304'] = "Dedicated sub-killer. Armed with three torpedo tubes, pair of torpedo defense systems and AA auto-cannon for use when surfaced.",
	['xss0303'] = "Can store, transport and repair aircraft. Armed with two pairs of AA auto-cannons.",
	['xss0403'] = "Fast and robust cruiser with devastating AA weapons and a powerful surface weapon",

	--Base Structures
	['xsb2101'] = "Low-end defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['xsb2104'] = "Anti-air tower. Designed to engage low-end aircraft.",
	['xsb2109'] = "Anti-naval defense system.",
	['xsb5101'] = "Restricts the movement of enemy units. Offers minimal protection from enemy fire.",
	['xsb2301'] = "Heavily armored, defensive tower that attacks land- and sea-based units. Does not engage aircraft or submerged units.",
	['xsb2204'] = "Anti-air tower. Designed to engage mid-level aircraft.",
	['xsb4201'] = "Tactical missile defense. Protection is limited to the structure's operational area.",
	['xsb4202'] = "Generates a protective shield around units and structures within its radius.",
	['xsb2205'] = "Anti-naval defense system. Employs torpedo defense system.",
	['xsb2304'] = "High-end anti-air tower. Designed to engage all levels of aircraft.",
	['xsb4302'] = "Strategic missile defense. Protection is limited to the structure's operational area.",
	['xsb4301'] = "Generates a heavy shield around units and structures within its radius.",
	['xsb2303'] = "Stationary, rapid-fire artillery. Provides decent impact damage across a small area.",
	['xsb2108'] = "Tactical missile launcher. Firing missiles requires resources.",
	['xsb5202'] = "Refuels and repairs most small aircraft. Air patrols will automatically use facility.",
	['xsb2302'] = "Stationary heavy artillery with excellent range, accuracy and damage potential. Requires resources to fire.",
	['xsb2305'] = "Strategic missile launcher. Constructing missiles costs resources.",
	['xsb2401'] = "Strategic missile launcher. Fired missile is so large, two strategic missile defenses are required to neutralize it.",

	--Engineer/Factories
	['xsl0105'] = "Tech 1 amphibious construction, repair, capture and reclamation unit.",
	['xsl0208'] = "Tech 2 amphibious construction, repair, capture and reclamation unit.",
	['xsl0309'] = "Tech 3 amphibious construction, repair, capture and reclamation unit.",

	['xsb0101'] = "Constructs Tech 1 land units. Upgradeable.",
	['xsb0102'] = "Constructs Tech 1 air units. Upgradeable.",
	['xsb0103'] = "Constructs Tech 1 naval units. Upgradeable.",
	['xsb0201'] = "Constructs Tech 2 land units. Upgradeable.",
	['xsb0202'] = "Constructs Tech 2 air units. Upgradeable.",
	['xsb0203'] = "Constructs Tech 2 naval units. Upgradeable.",
	['xsb0301'] = "Constructs Tech 3 land units. Highest tech level available.",
	['xsb0302'] = "Constructs Tech 3 air units. Highest tech level available.",
	['xsb0303'] = "Constructs Tech 3 naval units. Highest tech level available.",
	['xsb0304'] = "Summons Support Commander(s).",

	--Resource Structures
	['xsb1101'] = "Generates Energy. Construct next to other structures for adjacency bonus.",
	['xsb1102'] = "Generates Energy. Must be constructed on hydrocarbon deposits. Construct structures next to Hydrocarbon power plant for adjacency bonus.",
	['xsb1105'] = "Stores Energy. Construct next to power generators for enhanced power output or next to shields for enhanced shield performance.",
	['xsb1103'] = "Extracts Mass. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['xsb1104'] = "Mid-level Mass fabricator. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",
	['xsb1106'] = "Stores Mass. Construct next to extractors or fabricators for adjacency bonus.",
	['xsb1201'] = "Mid-level power generator. Construct next to other structures for adjacency bonus.",
	['xsb1202'] = "Mid-level Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['xsb1301'] = "High-end power generator. Construct next to other structures for adjacency bonus.",
	['xsb1302'] = "High-end Mass extractor. Must be constructed on Mass deposits. Construct structures next to Mass extractor for adjacency bonus.",
	['xsb1303'] = "High-end Mass fabricator. Requires large amounts of Energy. Construct next to other structures for adjacency bonus.",

	--Intelligence Structures
	['xsb3101'] = "Radar system with minimal range. Detects and tracks surface and air units.",
	['xsb3102'] = "Sonar system with minimal range. Detects and tracks naval units.",
	['xsb3202'] = "Sonar system with moderate range. Detects and tracks naval units.",
	['xsb3201'] = "Radar system with moderate range. Detects and tracks surface and air units.",
	['xsb4203'] = "Generates stealth field. Hides units and structures within its operational range. Countered by optical and Omni sensors.",
	['xsb3104'] = "High-end intelligence system. Provides maximum radar and sonar coverage. Counters enemy intelligence systems.",

	-- Patch Units
	['dea0202'] = "Combination fighter/bomber designed to engage both land and aerial units. Armed with linked AA railguns and heavy napalm carpet bombs.",
	['dra0202'] = "Combination fighter/bomber designed to engage both land and aerial units. Armed with Nano Dart launcher and separate missile launcher.",
	['daa0206'] = "The volatile and destructive nature of the Mercy's weapon system forced Aeon scientists to create a simple, expendable delivery system. As a result, the payload is attached to what is little more than a guided missile.",
	['del0204'] = "Fast moving, heavily armed assault bot. Armed with both a gatling plasma cannon and a heavy fragmentation grenade launcher.",
	['dal0310'] = "Mobile support unit. Designed to attack and destroy enemy shields. Weapon system is largely ineffective against enemy units.",
	['dab2102'] = "Gatling-style mortar launcher that fires high-explosive ordinance with a good degree of accuracy.",
	['drl0204'] = "Heavily armored rocket bot. Designed to engage and destroy heavily armored units.",
	['drs0102'] = "Unarmed stealth sub designed for reconnaissance missions. Equipped with anti-torpedo flares.",
}