-- Unit Upgrades Descriptions --
Description['uab2304-Radar_T2'] = "Installs a typical T2 radar on this structure."
Description['uab2304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['uab2304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."
Description['uab3304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['uab3304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."
Description['ueb2304-Radar_T2'] = "Installs a typical T2 radar on this structure."
Description['ueb2304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['ueb2304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."
Description['ueb3304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['ueb3304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."
Description['urb2304-Radar_T2'] = "Installs a typical T2 radar on this structure."
Description['urb2304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['urb2304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."
Description['urb3304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['urb3304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."
Description['xsb2304-Radar_T2'] = "Installs a typical T2 radar on this structure."
Description['xsb2304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['xsb2304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."
Description['xsb3304-Regen']    = "Installs a regenerative repair boost, increasing regen by 4x."
Description['xsb3304-Armor']    = "Installs 15% additional armor - at 30% of the original mass cost.  Adds +1 regen."

Description['urb0301-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['urb0301-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['urb0301-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['urb0301-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['urb0301-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['urb0301-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['urb0301'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['ueb0301-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['ueb0301-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['ueb0301-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['ueb0301-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['ueb0301-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['ueb0301-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['ueb0301'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['uab0301-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['uab0301-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['uab0301-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['uab0301-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['uab0301-Materiel_Exp'] = "This enhancement reduces material usage by 25% and energy maintenance drain by 20%.\nThe health of the structure is increased by 33% over the base amount."
Description['uab0301-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['uab0301-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['uab0301'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['xsb0301-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['xsb0301-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['xsb0301-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['xsb0301-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['xsb0301-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['xsb0301-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['xsb0301'] = "Constructs Tech 3 land units. Highest tech level available.\n\nProduction Enhancements available."

Description['urb0302-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['urb0302-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['urb0302-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['urb0302-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['urb0302-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['urb0302-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['urb0302'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['ueb0302-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['ueb0302-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['ueb0302-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['ueb0302-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['ueb0302-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['ueb0302-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['ueb0302'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['uab0302-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['uab0302-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['uab0302-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['uab0302-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['uab0302-Materiel_Exp'] = "This enhancement reduces material usage by 25% and energy maintenance drain by 20%.\nThe health of the structure is increased by 33% over the base amount."
Description['uab0302-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['uab0302-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['uab0302'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['xsb0302-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['xsb0302-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['xsb0302-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['xsb0302-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['xsb0302-Radar_T3'] = "Installs a typical T3 radar package onto the factory."
Description['xsb0302-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['xsb0302'] = "Constructs Tech 3 air units. Highest tech level available.\n\nProduction Enhancements available."

Description['urb0303-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['urb0303-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['urb0303-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['urb0303-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['urb0303-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['urb0303-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['urb0303'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."

Description['ueb0303-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['ueb0303-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['ueb0303-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['ueb0303-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['ueb0303-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['ueb0303-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['ueb0303'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."

Description['uab0303-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['uab0303-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['uab0303-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['uab0303-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['uab0303-Materiel_Exp'] = "This enhancement reduces material usage by 25% and energy maintenance drain by 20%.\nThe health of the structure is increased by 33% over the base amount."
Description['uab0303-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['uab0303-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['uab0303'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."

Description['xsb0303-Prod_Imp'] = "This engineering enhancement focuses on production speed.\n\nIncreases Build Speed by 30% over normal and enhances the self-repair of the structure."
Description['xsb0303-Prod_Adv'] = "This engineering enhancement further increases production speed.\n\nIncreases Build Speed by 60% over normal and further increases the self-repair capability of the structure."
Description['xsb0303-Materiel_Imp'] = "This enhancement reduces material usage by 10% and increases the HP of the structure."
Description['xsb0303-Materiel_Adv'] = "This enhancement reduces material usage by 20% and energy maintenance drain by 15%.\nThe HP of the structure is increased further."
Description['xsb0303-Sonar_T3'] = "Installs a typical T3 sonar package onto the factory."
Description['xsb0303-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['xsb0303'] = "Constructs Tech 3 naval units. Highest tech level available.\n\nProduction Enhancements available."

Description['uab4304'] = "The T3 Advanced Stealth Field Generator provides more radar & sonar jamming radius and is also usable on water."
Description['ueb4304'] = "The T3 Advanced Stealth Field Generator provides more radar & sonar jamming radius and is also usable on water."
Description['urb4304'] = "The T3 Advanced Stealth Field Generator provides more radar & sonar jamming radius and is also usable on water."
Description['xsb4304'] = "The T3 Advanced Stealth Field Generator provides more radar & sonar jamming radius and is also usable on water."

Description['uab5202-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['uab5202-Radar_T3'] = "Installs a typical T3 radar package onto the airpad."
Description['uab5202-Sonar_T3'] = "Installs a typical T3 sonar package onto the airpad."
Description['ueb5202-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['ueb5202-Radar_T3'] = "Installs a typical T3 radar package onto the airpad."
Description['ueb5202-Sonar_T3'] = "Installs a typical T3 sonar package onto the airpad."
Description['urb5202-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['urb5202-Radar_T3'] = "Installs a typical T3 radar package onto the airpad."
Description['urb5202-Sonar_T3'] = "Installs a typical T3 sonar package onto the airpad."
Description['xsb5202-Shield'] = "Installs a custom shield dome into the factory. While not very large, the shield is robust and regenerates quickly. Does not benefit from any adjacent structures."
Description['xsb5202-Radar_T3'] = "Installs a typical T3 radar package onto the airpad."
Description['xsb5202-Sonar_T3'] = "Installs a typical T3 sonar package onto the airpad."
