name = "BrewLAN for LOUD"
uid = "25D57D85-7D84-27HT-A501-BR3WL4N000079" -- this is UID hard coded into hook/lua/game.lua and hook/lua/system/blueprints.lua
version = 7.0
copyright = "� 2009 - 2023 Sean Wheeldon"
description = "Adds most of the BrewLAN units, specifically tailored for use with The LOUD Project"
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_LOUD/documentation/BrewLAN-LOUD-full.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
