name = "BrewLAN for LOUD"
uid = "25D57D85-7D84-27HT-A501-BR3WL4N000079" -- this is UID hard coded into hook/lua/game.lua and hook/lua/system/blueprints.lua
version = 0.66
copyright = "� 2009 - 2018 Sean Wheeldon"
description = "BrewLAN for LOUD Version 0.66. Base Units. Partially AI enabled. "
author = "Sean Wheeldon"
icon = "/mods/BrewLAN_LOUD/documentation/BrewLAN-LOUD-full.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = { }
before = { }
after = { }
