name = "BrewLAN Debug Tools"
uid = "2529ea71-93ef-41a6-b552-LOGS0000000009"
version = 1
copyright = "© 2017–2018 Sean Wheeldon"
description = "Debug and testing tools, primarily for unit development. Not for real matches."
author = "Balthazar"
icon = "/mods/BrewLAN_Plenae/Logger/debug.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
conflicts = {  }
before = {  }
after = {  }
