layout = {
	['top_tab_btn_sel_bmp'] = {left = 9, top = 5, width = 63, height = 45, },
	['top_tab_btn_down_bmp'] = {left = 9, top = 5, width = 63, height = 45, },
	['top_tab_btn_over_bmp'] = {left = 9, top = 5, width = 63, height = 45, },
	['top_tab_btn_up_bmp'] = {left = 9, top = 5, width = 63, height = 45, },
	['top_tab_btn_dis_bmp'] = {left = 9, top = 5, width = 63, height = 45, },
	['mid_tab_btn_sel_bmp'] = {left = 8, top = 5, width = 64, height = 44, },
	['mid_tab_btn_down_bmp'] = {left = 8, top = 5, width = 64, height = 44, },
	['mid_tab_btn_over_bmp'] = {left = 8, top = 5, width = 64, height = 44, },
	['mid_tab_btn_up_bmp'] = {left = 8, top = 5, width = 64, height = 44, },
	['mid_tab_btn_dis_bmp'] = {left = 8, top = 5, width = 64, height = 44, },
	['bot_tab_btn_sel_bmp'] = {left = 9, top = 4, width = 63, height = 45, },
	['bot_tab_btn_down_bmp'] = {left = 9, top = 4, width = 63, height = 45, },
	['bot_tab_btn_over_bmp'] = {left = 9, top = 4, width = 63, height = 45, },
	['bot_tab_btn_up_bmp'] = {left = 9, top = 4, width = 63, height = 45, },
	['bot_tab_btn_dis_bmp'] = {left = 9, top = 4, width = 63, height = 45, },
}
