layout = {
	['l_chat-btn'] = {left = 51, top = 137, width = 28, height = 28, leftOffset = 0, topOffset = 0, },
	['l_text'] = {left = 58, top = 54, width = 267, height = 105, leftOffset = 0, topOffset = 0, },
	['drop-box_brd_lr'] = {left = 314, top = 149, width = 16, height = 12, leftOffset = 1, topOffset = 0, },
	['drop-box_brd_lm'] = {left = 100, top = 149, width = 8, height = 12, leftOffset = 0, topOffset = 0, },
	['drop-box_brd_ll'] = {left = 77, top = 149, width = 16, height = 12, leftOffset = 1, topOffset = 0, },
	['drop-box_brd_vert_r'] = {left = 319, top = 108, width = 8, height = 8, leftOffset = 0, topOffset = 0, },
	['drop-box_brd_m'] = {left = 100, top = 108, width = 8, height = 8, leftOffset = 0, topOffset = 0, },
	['drop-box_brd_vert_l'] = {left = 77, top = 108, width = 8, height = 8, leftOffset = 0, topOffset = 0, },
	['drop-box_brd_ur'] = {left = 314, top = 95, width = 16, height = 16, leftOffset = 1, topOffset = 1, },
	['drop-box_brd_horz_um'] = {left = 100, top = 95, width = 8, height = 16, leftOffset = 0, topOffset = 1, },
	['drop-box_brd_ul'] = {left = 77, top = 95, width = 16, height = 16, leftOffset = 1, topOffset = 1, },
	['l_camera-icon_btn'] = {left = 326, top = 138, width = 29, height = 26, leftOffset = 0, topOffset = 0, },
	['l_scroll-description'] = {left = 326, top = 54, width = 28, height = 82, leftOffset = 0, topOffset = 0, },
	['l_tab-lock-handles'] = {left = 29, top = 34, width = 22, height = 39, leftOffset = 0, topOffset = 0, },
	['l_drag-handles'] = {left = 32, top = 17, width = 340, height = 158, leftOffset = 0, topOffset = 0, },
	['chat_brd_lr'] = {left = 319, top = 120, width = 44, height = 48, leftOffset = 1, topOffset = 1, },
	['chat_brd_lm'] = {left = 85, top = 120, width = 8, height = 48, leftOffset = 0, topOffset = 1, },
	['chat_brd_ll'] = {left = 42, top = 120, width = 44, height = 48, leftOffset = 0, topOffset = 1, },
	['chat_brd_vert_r'] = {left = 319, top = 72, width = 44, height = 8, leftOffset = 1, topOffset = 0, },
	['chat_brd_m'] = {left = 85, top = 72, width = 8, height = 8, leftOffset = 0, topOffset = 0, },
	['chat_brd_vert_l'] = {left = 42, top = 72, width = 44, height = 8, leftOffset = 0, topOffset = 0, },
	['chat_brd_ur'] = {left = 319, top = 27, width = 44, height = 48, leftOffset = 1, topOffset = 1, },
	['chat_brd_horz_um'] = {left = 85, top = 27, width = 8, height = 48, leftOffset = 0, topOffset = 1, },
	['chat_brd_ul'] = {left = 42, top = 27, width = 44, height = 48, leftOffset = 0, topOffset = 1, },
}
