version = 3
ScenarioInfo = {
  name = 'Hellgate - Low Tide',
  description = '<LOC Hellgate_LowTide_Description>Forget the toy boats - roll the heavy metal !',
  type = 'skirmish',
  starts = true,
  preview = '',
  size = {2048, 2048},
  map = '/maps/Hellgate_LowTide/Hellgate_LowTide.scmap',
  save = '/maps/Hellgate_LowTide/Hellgate_LowTide_save.lua',
  script = '/maps/Hellgate_LowTide/Hellgate_LowTide_script.lua',
  map_version = '1',
  norushradius = 75,
  Configurations = {
    ['standard'] = {
      teams = {
        {
          name = 'FFA',
          --armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8'},
          armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8', 'ARMY_9', 'ARMY_10', 'ARMY_11', 'ARMY_12'},
        },
      },
      customprops = {},
    },
  },
  norushoffsetX_ARMY_1 = 0,
  norushoffsetY_ARMY_1 = 0,
  norushoffsetX_ARMY_2 = 2,
  norushoffsetY_ARMY_2 = 1,
  norushoffsetX_ARMY_3 = 0,
  norushoffsetY_ARMY_3 = 0,
  norushoffsetX_ARMY_4 = 0,
  norushoffsetY_ARMY_4 = 0,
  norushoffsetX_ARMY_5 = 0,
  norushoffsetY_ARMY_5 = 0,
  norushoffsetX_ARMY_6 = 0,
  norushoffsetY_ARMY_6 = 0,
  norushoffsetX_ARMY_7 = 0,
  norushoffsetY_ARMY_7 = 0,
  norushoffsetX_ARMY_8 = 0,
  norushoffsetY_ARMY_8 = 0,
}
