-- BLACK OPS Unit Descriptions

--Aeon

Description['baa0309'] = "Illuminate can ferry large amounts of units across the battlefield. This special transport makes up for is lack of armor with a teleportation device."
Description['bal0110'] = "The basic Aeon sniper unit must be stationary to fire its long range weapon.  Its low rate of fire makes it vulnerable in skirmish situations."
Description['bab2306'] = "Aria is the advanced version of the Oblivion point defense emplacement.  With greater range its high powered continuous beam weapon is capable of inflicting awesome damage."
Description['bal0206'] = "Zealot is the standard Aeon ground support/assault unit. Good speed, armor and decent firepower make it quite effective."
Description['bal0310'] = "Wraith features a smaller direct fire version of the Sonance Artillery weapon and two side mounted weapons. As a potent hovercraft it makes an excellent unit either on land or water."
Description['bal0401'] = "Inquisitor was designed specifically for the role of bombarding bases. Equipped with a downscaled version of the Artemis' Fire, it teleports its charges into the sky above its target. This process requires considerable power and leaves little room for defensive systems or secondary weapons."
Description['bal0403'] = "Interrogator is the ultimate sniper.  With radar, radar and sonar stealth, and a devastating long range implosion weapon, it makes an ideal infiltrator or siege unit."
Description['bab2308'] = "The Purifier fires a Tactical Missle that splits above the target area showering it with explosives."
Description['bab4307'] = "Long range Anti-Missle defense. Long range but slow rate of fire."
Description['bab4209'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. Can be upgraded for a larger area of effect."
Description['bab4309'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. The affected area is larger than the T2 version."
Description['bab1106'] = "Advanced Storage building, provides bonus for both Mass and Energy producing structures as well as storing Mass and Energy."
Description['bab2303'] = "Medium yield energy mortar, fires quick bursts at enemies in range."
Description['bal0402'] = "Genesis is essentially a mobile tactical missile platform with a direct fire Oblivion cannon for close-in work, designed to provide long range fire support and tactical missile defense, it also features the unique Maelstrom field which continuously damages all enemy units which get too close."
Description['balk003'] = "Advanced mobile anti-air unit. The Redeemer carries safely inside it's covers a modified anti-air variant of the powerful Serpentine missile."

--UEF

Description['belk002'] = "Advanced mobile anti-air unit. The Cougar is armed with dual high precision AA gatling cannons, capable of hitting even the faster high-end planes."
Description['bel0307'] = "A refined version of the Juggernaut, the Helltank eliminates the skin shield in favor of a railgun, more speed and low-altitude AA capability. Aptly named for its large weapons array, the Helltank is a force to be reckoned with."
Description['bes0402'] = "The Conquest Dreadnought carries three X-Cannons which fires shells filled with concentrated anti-matter, it also carries 8 long ranged cannons and 8 flak guns. Capable of providing superb shore bombardment and adequate air defense."
Description['bea0402'] = "Unsatisfied with the performance of the original Citadel, it was redesigned with a greater focus on Air Superiority. It lost much of it's Air to Ground Weaponry in favor of boosted Air-to-Air Weapons for a great focus upon Air Superiority."
Description['bea0403'] = "The Citadel is an attempt to bring the firepower of Fatboy into a flying form. Removing the factory and bubble shield in favor of AA weapons makes it a versatile ground support package."
Description['bel0308'] = "Mobile artillery support bot, fires napalm shells at the target while moving and carries secondary short range gauss cannons."
Description['bel0402'] = "UEF designers revamped the original Goliath design, the new Goliath features Incinerator Flamethrowers, the \"Mega Beam Cannon\", tracking tactical missiles, TMD, and air defense drones."
Description['bel0211'] = "The Inferno uses a pair of Flamethrowers to burn enemies to a crisp, heavily armored, if its fuel tank is ruptured by weapons, it results in a violent explosion."
Description['beb4209'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. Can be upgraded for a larger area of effect."
Description['beb4309'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. The affected area is larger than the T2 version."
Description['beb1106'] = "Advanced Storage building, provides bonus for both Mass and Energy producing structures as well as storing Mass and Energy."
Description['beb2303'] = "Rapid-Fire Howitzer Emplacement, showers the target area with low yield explosives, uses energy to fire."
Description['xel0307'] = "The Jug is the ultimate UEF battletank - designed to master many situations - it suffers only from a lack of speed."

--Cybran

Description['brl0205'] = "Ambush Assault unit. Scorpion is equipped with a personal stealth field, and becomes cloaked when standing still; allowing for ambushes against enemy forces."
Description['brl0307'] = "Medium Range Artillery Unit. The Hailfire fires a slavo of rockets at the target which detonate in a Low Yield EMP Blast stunning enemy units."
Description['brl0401'] = "Ultimate weapon in the Cybran Military, derived from the original Basilisk design, while in assault mode it is armed with an Experimental Electron Accelerator Cannon, a pair of Electron Scrambler Cannons, two Electron Bolters, Nanite swarm missiles and Microwave Nanite Anti-air missiles. In Siege mode it sports the original Plasma cannon and LOA TML system. The AI is still known to occasionally wander off on its own to attack the enemy."
Description['brs0304'] = "The Reaper serves as an escort and a battlecriuser, capable of fighting every type of enemy."
Description['brs0402'] = "Pride of the Cybran Navy, the Seadragon Dreadnought is armed with 2 X-Cannons, several deck cannons, AA, and torpedoes; enemies shake in fear at the sight of this vessel. Also able to repair and refuel aircraft in the field."
Description['ura0309'] = "The Vanisher is the Cybran's heavy transport, equipped with Cloak Field Generators, it can become very useful to a clever Commander. Suffers from limited capacity."
Description['bra0409'] = "The Gargantuan transport, capable of transporting upto 20 tier 3 units. Equipped with multiple AA lasers, ground attack cannons and a unique EMP weapon, Gargantua can get you where you need to go."
Description['brb2306'] = "Fires a Microwave laser along with a high concentration of electromagnetic energy into the target, causing it to explode damaging and shutting down all units in the affected area."
Description['brs0305'] = "Heavy attack sub. Armed with the latest advanced Krill torpedos from the cybran Navy. Uses twin bolters when surfaced and come equiped with a Torpedo Redirection System."
Description['brb4401'] = "The Shadow creates an energy field around it and bends light to make it and anyting else close by invisible visual sensors."
Description['brb4209'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. Can be upgraded for a larger area of effect."
Description['brb4309'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. The affected area is larger than the T2 version."
Description['brb1106'] = "Advanced Storage building, provides bonus for both Mass and Energy producing structures as well as storing Mass and Energy."
Description['brb2303'] = "Rapid-Fire rocket launcher, showers the target area with low yield explosives, uses energy to fire."
Description['brlk001'] = "Advanced mobile anti-air unit. Utilizing a crude but effective target painter the Bouncer can lead it's missile salvo even to the fastest advanced aircraft. It can also use it's missiles as anti-ground rockets without guidance."
Description['brlk005'] = "Advanced mobile anti-air unit. Utilizing a crude but effective target painter the Bouncer can lead it's missile salvo even to the fastest advanced aircraft. It can also use it's missiles as anti-ground rockets without guidance."

--Seraphim
Description['bsb2402'] = "The Rift can stabilize a connection to the Quantum realm. Once this is done a Seraphim Commander can summon an endless amount of reinforcements. Each unit summoned draws power to sustain itself in this realm.  If there is not enough available then summoned units will perish."
Description['bsb0405'] = "The Lambda Field Generator generates a field to repel or destroy enemy projectiles (not beams). This structure also mounts two Quantum Storm Cannons."
Description['bsl0106'] = "The Ilhaas sends out signals which force enemy units to think it is a dangerous target, this makes the unit draw enemy fire while its allies fire back."
Description['bsl0206'] = "The Ula Ilhaas sends out signals which force enemy units to think it is a dangerous target, this makes the unit draw enemy fire while its allies fire back."
Description['bsl0306'] = "Ultha Ilhaas sends out signals which force enemy units to think it is a dangerous target, this makes the unit draw enemy fire while its allies fire back."
Description['bsl0406'] = "Seth Ilhaas  sends out signals which force enemy units to think it is a dangerous target, this makes the unit draw enemy fire while its allies fire back. Equipped with Basic regeneration field and radar, this makes it an important part of any Sera assault group"
Description['bsl0310'] = "After seeing the usefulness of Seige Assault bots, the seraphim attemped their own design, incorporating a Dual Tau Cannon, TMD and a Lambda Field generator the Ilthysathuum is a very deadly weapon."
Description['bsa0309'] = "The Vishathal-Atah is an advanced transport with weak armor, it makes up for this with its large carrying capacity, a limited Lambda Field System and its speed."
Description['bsa0310'] = "Armed with high yield missiles and a pair of shield disruptors the Vulthatha-Ioz can take on large groups of enemies and break through even the toughest shields with ease."
Description['bss0401'] = "High end naval unit. Armed with 3 heavy Quarnon Cannons, 4 anti-vessel beams and 4 AA Artillery cannon; this beast made its appearance shortly after the Cybran and UEF coalition forces unleashed the Conquest and Seadragon against the seraphim. This vessel also holds 2 experimental canons, that when impact are capable of summoning an Energy Being similar to the one made by the Ythotha, though considerably weaker."
Description['bss0206'] = "This unit was built for the sole purpose of bombarding fortified bases where the Cruiser or Destroyer proved to be ineffective. Its slow turret speed makes it less effective at hitting fast mobile targets, allowing faster ships to close in and engage."
Description['bss0306'] = "Heavy Assault & Advanced Sensor Frigate, this unit is heavily armed for naval combat; armed with 3 Shie-eih Auto-Cannons, 2 Ultrachromatic Beam Generators, 2 Losaare AA Autocannons, and an Unstable Phason Generator. It also has Radar, Sonar, and is capable of submerging itself underwater."
Description['bsb2306'] = "Fires an energy projectile that creates a small lightning entity that will attack nearby enemy units."
Description['bsb4209'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. Can be upgraded for a larger area of effect."
Description['bsb4309'] = "Creates and amplifies the effects of Quantum Wakes, preventing enemies from teleporting units within the affected area. The affected area is larger than the T2 version."
Description['bsb1106'] = "Advanced Storage building, provides bonus for both Mass and Energy producing structures as well as storing Mass and Energy."
Description['bsl0401'] = "Experimental hover tank, carries small beam drones into battle, also armed with an experimental Phason Beam which increases in damage the longer the beam is active."
Description['bslk004'] = "Advanced mobile multipurpose unit. Using an uncontained power generator core the Uyanah can unleash powerful and swift lightning strikes at aerial targets. It can also generate a secondary flux to a grounded target."

--Hawkeye Upgrades

Description['uel0001-hues'] = "Replaces the Tech 3 Engineering Suite. Allows the ACU to contruct Experimental class units and further increases the ACU's build speed and maximum health."
Description['url0001-hres'] = "Replaces the Tech 3 Engineering Suite. Allows the ACU to contruct Experimental class units and further increases the ACU's build speed and maximum health."
Description['ual0001-haes'] = "Replaces the Tech 3 Engineering Suite. Allows the ACU to contruct Experimental class units and further increases the ACU's build speed and maximum health."
Description['xsl0001-hses'] = "Replaces the Tech 3 Engineering Suite. Allows the ACU to contruct Experimental class units and further increases the ACU's build speed and maximum health."
