ScenarioInfo = {
  name = 'Painted Desert 40 - 5 on 5',
  description = '<LOC Painted Desert 40_Description>Painted Desert - Expanded to 40km - 5 on 5.   This map features a simplified amphibious path layout, specifically to see if it helps performance.',
  type = 'skirmish',
  starts = true,
  preview = '',
  size = {2048, 2048},
  map = '/maps/Painted Desert 40/Painted Desert 40.scmap',
  save = '/maps/Painted Desert 40/Painted Desert 40_save.lua',
  script = '/maps/Painted Desert 40/Painted Desert 40_script.lua',
  norushradius = 47,
  map_version = 6,
  Configurations = {
    ['standard'] = {
      teams = {
        {
          name = 'FFA',
          --armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8'},
          armies = {'ARMY_1', 'ARMY_2', 'ARMY_3', 'ARMY_4', 'ARMY_5', 'ARMY_6', 'ARMY_7', 'ARMY_8', 'ARMY_9', 'ARMY_10'},
        },
      },
      customprops = {},
    },
  },
  norushoffsetX_ARMY_1 = 0,
  norushoffsetY_ARMY_1 = 0,
  norushoffsetX_ARMY_2 = 0,
  norushoffsetY_ARMY_2 = 0,
  norushoffsetX_ARMY_3 = 0,
  norushoffsetY_ARMY_3 = 0,
  norushoffsetX_ARMY_4 = 0,
  norushoffsetY_ARMY_4 = 0,
  norushoffsetX_ARMY_5 = 0,
  norushoffsetY_ARMY_5 = 0,
  norushoffsetX_ARMY_6 = 0,
  norushoffsetY_ARMY_6 = 0,
  norushoffsetX_ARMY_7 = 0,
  norushoffsetY_ARMY_7 = 0,
  norushoffsetX_ARMY_8 = 0,
  norushoffsetY_ARMY_8 = 0,
}
