layout = {
	['bar-top_scr_down'] = {left = 0, top = 10, width = 27, height = 9, },
	['bar-top_scr_over'] = {left = 0, top = 10, width = 27, height = 9, },
	['bar-top_scr_up'] = {left = 4, top = 11, width = 19, height = 8, },
	['bar-top_scr_dis'] = {left = 4, top = 11, width = 19, height = 8, },
	['bar-mid_scr_down'] = {left = 1, top = 1, width = 26, height = 18, },
	['bar-mid_scr_over'] = {left = 1, top = 1, width = 26, height = 18, },
	['bar-mid_scr_up'] = {left = 4, top = 1, width = 19, height = 18, },
	['bar-mid_scr_dis'] = {left = 4, top = 1, width = 19, height = 18, },
	['bar-bot_scr_down'] = {left = 0, top = 1, width = 27, height = 9, },
	['bar-bot_scr_over'] = {left = 0, top = 1, width = 27, height = 9, },
	['bar-bot_scr_up'] = {left = 4, top = 1, width = 19, height = 7, },
	['bar-bot_scr_dis'] = {left = 4, top = 1, width = 19, height = 7, },
	['arrow-up_scr_down'] = {left = 0, top = 0, width = 28, height = 20, },
	['arrow-up_scr_over'] = {left = 0, top = 0, width = 28, height = 20, },
	['arrow-up_scr_up'] = {left = 0, top = 0, width = 28, height = 20, },
	['arrow-up_scr_dis'] = {left = 3, top = 0, width = 23, height = 18, },
	['arrow-down_scr_down'] = {left = 0, top = 0, width = 28, height = 20, },
	['arrow-down_scr_over'] = {left = 0, top = 0, width = 28, height = 20, },
	['arrow-down_scr_up'] = {left = 0, top = 0, width = 28, height = 20, },
	['arrow-down_scr_dis'] = {left = 3, top = 1, width = 23, height = 17, },
}
