layout = {
	['bar-top_scr_down'] = {left = 8, top = 8, width = 19, height = 6, },
	['bar-top_scr_over'] = {left = 8, top = 8, width = 19, height = 6, },
	['bar-top_scr_up'] = {left = 8, top = 8, width = 19, height = 6, },
	['bar-top_scr_dis'] = {left = 8, top = 8, width = 19, height = 6, },
	['bar-mid_scr_down'] = {left = 8, top = 14, width = 19, height = 8, },
	['bar-mid_scr_over'] = {left = 8, top = 14, width = 19, height = 8, },
	['bar-mid_scr_up'] = {left = 8, top = 14, width = 19, height = 8, },
	['bar-mid_scr_dis'] = {left = 8, top = 14, width = 19, height = 8, },
	['bar-bot_scr_down'] = {left = 8, top = 22, width = 19, height = 6, },
	['bar-bot_scr_over'] = {left = 8, top = 22, width = 19, height = 6, },
	['bar-bot_scr_up'] = {left = 8, top = 22, width = 19, height = 6, },
	['bar-bot_scr_dis'] = {left = 8, top = 22, width = 19, height = 6, },
	['arrow-up_scr_down'] = {left = 0, top = 0, width = 36, height = 34, },
	['arrow-up_scr_over'] = {left = 0, top = 0, width = 36, height = 34, },
	['arrow-up_scr_up'] = {left = 0, top = 0, width = 36, height = 34, },
	['arrow-up_scr_dis'] = {left = 0, top = 0, width = 36, height = 34, },
	['arrow-down_scr_down'] = {left = 0, top = 1, width = 36, height = 35, },
	['arrow-down_scr_over'] = {left = 0, top = 1, width = 36, height = 35, },
	['arrow-down_scr_up'] = {left = 0, top = 2, width = 36, height = 34, },
	['arrow-down_scr_dis'] = {left = 0, top = 2, width = 36, height = 34, },
	['back_scr_top'] = {left = 4, top = 4, width = 27, height = 10, },
	['back_scr_mid'] = {left = 4, top = 14, width = 27, height = 8, },
	['back_scr_bot'] = {left = 4, top = 22, width = 27, height = 10, },
}
