layout = {
	['drag-handle-ur_btn_down'] = {left = 11, top = 5, width = 58, height = 88, },
	['drag-handle-ur_btn_over'] = {left = 11, top = 5, width = 58, height = 88, },
	['drag-handle-ur_btn_up'] = {left = 11, top = 5, width = 58, height = 88, },
	['drag-handle-ur_btn_dis'] = {left = 11, top = 5, width = 58, height = 88, },
	['drag-handle-ul_btn_down'] = {left = 13, top = 5, width = 58, height = 88, },
	['drag-handle-ul_btn_over'] = {left = 13, top = 5, width = 58, height = 88, },
	['drag-handle-ul_btn_up'] = {left = 13, top = 5, width = 58, height = 88, },
	['drag-handle-ul_btn_dis'] = {left = 13, top = 5, width = 58, height = 88, },
	['drag-handle-ll_btn_down'] = {left = 13, top = 3, width = 58, height = 88, },
	['drag-handle-ll_btn_over'] = {left = 13, top = 3, width = 58, height = 88, },
	['drag-handle-ll_btn_up'] = {left = 13, top = 3, width = 58, height = 88, },
	['drag-handle-ll_btn_dis'] = {left = 13, top = 3, width = 58, height = 88, },
	['drag-handle-lr_btn_down'] = {left = 10, top = 3, width = 58, height = 88, },
	['drag-handle-lr_btn_over'] = {left = 10, top = 3, width = 65, height = 93, },
	['drag-handle-lr_btn_up'] = {left = 10, top = 3, width = 65, height = 93, },
	['drag-handle-lr_btn_dis'] = {left = 10, top = 3, width = 65, height = 93, },
}
