
	-- AEON
	Description['wal0401'] = "A slightly bigger, slightly improved Galactic Colossus."
	Description['wal4404'] = "Close Combat Light Experimental with AA."
	Description['was0332'] = "Heavy Support Cruiser, providing limited shield cover and excellent air defense."

    -- UEF
    Description['web0404'] = "Heavily armed defensive fortification for securing naval yards.\nExcellent underwater vision\nHighly regenerative.\nCustomizable with either Shield or Radar."
    Description['web0404-Shield'] = "Adds a Tech 2 level dome shield to the unit."
    Description['web0404-Radar_T3'] = "Adds a Tech 3 radar to the unit."
    Description['web4301'] = "Designed using stolen Cybran tech, this beam-based tactical missile defense system is highly effective, but costly."
	Description['wel0207'] = "Mobile beam-based Tactical Missile Defense. Costly, but 100% accurate at short ranges."
	Description['wel0302'] = "The Wrecker is a T3 level Mongoose - dual Gatling guns with low altitude AA capability, personal shield and good speed."
	Description['wel0304'] = "A very tough amphibious tank."
	Description['wel0305'] = "Partner to the IronFist - bringing AA and TMD to the heaviest units that can be created at a factory."
	Description['wel0309'] = "Mobile SAM. Fires short range AA missiles. Very effective versus gunships, with heavier armor than the Cougar."
    Description['wel0341'] = "The need for artillery in amphibious operations finds its answer in the Walrus."
    Description['wel0401'] = "The Wyvern is a combat refit of the original FatBoy. Remove the factory and add artillery. Designed to provide ranged support for battlegroups."
	Description['wel0416'] = "Taking a cue from the Cybran Basilisk, Dragonite attempts to bring the same features to the table; lots of weapons, and regenerative."
	Description['wel1409'] = "Experimental Tank - The Wyvern version of Fatboy II. Less total firepower - more range."
	Description['wel1409-sgf'] = "Creates a protective shield around the Fatboy 2. Requires Energy to run."
    Description['wel4404'] = "The Star Adder is a Medium Mech blessed with very good speed, solid firepower, radar, and personal stealth.\nIntended to replace the less successful Rampage"
	Description['wes0303'] = "Heavily armoured Escort ship. Can attack all types of targets, including submarines and aircraft."

	-- CYBRAN
    Description['wra0401'] = "A field revision of the Ripper, focused on ground attack but with less air defense."
    Description['wrl0207'] = "A poor attempt by Cybran engineers to bring mobile shields onto the battlefield."
	Description['wrl0301'] = "Heavily armoured amphibious tank, equipped with personal stealth."
	Description['wrl0305'] = "A very quick sniper with radar stealth. Its weapon is only partially effective against shields. Unlike other snipers, while capable of firing on the move, it is quite inaccurate."
	Description['wrl0309'] = "Mobile SAM with radar onboard. Effective against high-end enemy air units."
	Description['wrl1466'] = "The Storm Strider is the refinement of many key Cybran concepts; quick, hard hitting, regenerative."

	-- SERAPHIM
	Description['wsl0202'] = "A quick, simple, effective, main battle tank design."
	Description['wsl0205'] = "A shielded, speedy, but non-amphibious protector bot."
	Description['wsl0308'] = "A solid punch, with stunning on a rapid assault chassis."
	Description['wsl0404'] = "Experimental Mobile Field Artillery with a local close defense weapon and AA."

    -- Battle Pack AEON ACU STUFF
    Description['wal0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
    Description['wal0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3000 Health\nArmour Regen:+20\nBuild Speed:+30"
    Description['wal0001-cd'] = "Creates a Quantum Stasis Field around the ACU. Immobilizes enemy units within its radius. High Energy Consumption.\n\nInstalls Chrono Dampener"
    Description['wal0001-plg'] = "Adds a Phason Laser to the ACU. Increases Health and Regen.\n\n+5000 Health\n+25 Armour Regen\nInstalls Phason Laser Generator"
    Description['wal0001-ess'] = "Greatly expands the range of the standard onboard ACU sensor systems.\n\n+50 Vision Radius\n+100 Omni Radius"
    Description['wal0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+6000 Health\nArmour Regen:+40\nBuild Speed:+80"
    Description['wal0001-fpu'] = "Enhancments the plasma capacitors of the disruptor. Increases Damage.\n\n+100 Disruptor Damage"
    Description['wal0001-ras'] = "Increases ACU's resource generation.\n\nNew Mass Production:18\nNew Energy Production:2700"
    Description['wal0001-eras'] = "Requires Resource Allocation System. Further increases ACU's resource generation.\n\nNew Mass Production:36\nNew Energy Production:5400"
    Description['wal0001-ptsg'] = "Creates a protective shield around the ACU. Requires Energy to run.\n\nShield Health:29000\nShield Regen:37\nShield Type:Personal\nShield Mainntenance:250"
    Description['wal0001-phtsg'] = "Enhances the protective shield around the ACU. Requires Energy to run. \n\nShield Health:44000\nShield Regen:44\nShield Type:Personal\nShield Mainntenance:500"
    Description['wal0001-phtsg_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nEnables Sonic Pulse Batteries"
    Description['wal0001-eras_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nEnables Sonic Pulse Batteries"
    Description['wal0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
    Description['wal0001-hsa'] = "Adds Anti-Missile Capabilities.\n\nEnables TML Defenses"
    Description['wal0001-spd'] = "Increases ACU speed by 50%. \n\nIncreased speed by 50%"
    Description['wal0001-ctl'] = "Enables teh ACU's Chrono Torpedo Tube System.\n\nInstalls Torpedo Launcher"

	-- Battle Pack UEF ACU STUFF
    Description['wel0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
    Description['wel0001-tm'] = "Mounts a tactical cruise missile launcher onto the back of the ACU.\n\nInstalls Tactical Missile Launcher"
    Description['wel0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3000 Health\nArmour Regen:+20\nBuild Speed:+30"
    Description['wel0001-dsu'] = "Greatly increases the speed at which the ACU repairs itself.\n\nRegen Rate:200"
    Description['wel0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+6000 Health\nArmour Regen:+15\nBuild Speed:+90"
    Description['wel0001-hamc'] = "Increases main cannon's damage output by several factors. Also increases range of main cannon and Overcharge.\n\n+100 Zepher Damage\nNew Range:30"
    Description['wel0001-srtn'] = "Adds a short-range tactical nuke.\n\nInstalls Nuclear Tactical Missile Launcher"
    Description['wel0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
    Description['wel0001-sgf'] = "Expands the radius of the ACU's personal shield. Requires Energy to run.\n\nShield Health:36000\nShield Regen:42\nShield Type:Bubble\nBubble Size:16\nShield Mainntenance:500"
    Description['wel0001-isb'] = "Increases ACU's resource generation.\n\nNew Mass Production:14\nNew Energy Production:3300"
    Description['wel0001-psg'] = "Creates a protective shield around the ACU. Requires Energy to run.\n\nShield Health:24000\nShield Regen:35\nShield Type:Personal\nShield Mainntenance:250"
    Description['wel0001-hpsg'] = "Enables a pair of Anti-Air Batteries.\n\nInstalls Flayer SAM Launchers"
    Description['wel0001-led'] = "Engineering Drone acts as a secondary Engineer. Assists the ACU where applicable.\n\nInstalls Left Engineering Drone"
    Description['wel0001-red'] = "Adds a second Engineering Drone. Requires an initial Engineering Drone.\n\nInstalls Right Engineering Drone"
	Description['wel0001-sg'] = "Enables a pair of shoulder mounted gauss guns.\n\nInstalls Shoulder Gauss Cannons"
	Description['wel0001-gat'] = "Enables the ACUs secondary weapon system.\n\nInstalls Heavy Plasma Gatling Cannon"
	Description['wel0001-atl'] = "Enables a Angler Torpedo Launcher on the ACU to defend against naval attacks while submerged.\n\nInstalls Torpedo Launcher"

	-- Battle Pack CYBRAN ACU STUFF
    Description['wrl0001'] = "Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
    Description['wrl0001-ras'] = "Increases ACU's resource generation.\n\nNew Mass Production:15\nNew Energy Production:4000"
    Description['wrl0001-pcg'] = "Cloaks the ACU from optical sensors and increases maximum health. Can be detected by Omni Sensors. Requires Energy to run.\n\nInstalls Cloak Generator"
    Description['wrl0001-psg'] = "Hides the ACU from radar. Requires Energy to run.\n\nEnables Radar Stealth"
    Description['wrl0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
    Description['wrl0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3500 Health\nArmour Regen:+20\nBuild Speed:+30"
    Description['wrl0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+7000 Health\nArmour Regen:+15\nBuild Speed:+90"
    Description['wrl0001-acu'] = "Increases main cannon's rate of fire and range. Also increases range of the Molecular Ripper and Overcharge.\n\nNew Range:30\nNew RoF:2"
    Description['wrl0001-dual'] = "Equips the ACU with a second ripper cannon.\n\nInstalls Secondary Ripper Cannon"
    Description['wrl0001-ntt'] = "Equips the ACU with a standard Cybran Nanite torpedo tube and sonar.\n\nInstalls Torpedo Launcher"
	Description['wrl0001-fc'] = "Increases the damage of all the ACUs weapon Systems.\n\nAnti-Air Damage:+25\nTorpedo Damage:+50\nRipper Damage:+100"
    Description['wrl0001-cpsg'] = "Equips the ACU with a Personal Shield Generator. Requires energy to run.\n\nShield Health:24000\nShield Regen:35\nShield Type:Personal\nShield Mainntenance:250"
    Description['wrl0001-hcpsg'] = "Upgrades the ACU's personal shield.\n\nShield Health:44000\nShield Regen:44\nShield Type:Personal\nShield Mainntenance:500"
    Description['wrl0001-eras_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nInstalls Electron Autocannons"
    Description['wrl0001-hcpsg_aa'] = "Enables a pair of Anti-Air batteries on the ACU.\n\nInstalls Electron Autocannons"

	-- SERAPHIM ACU STUFF
	Description['wsl0001'] = "<LOC Unit_Description_0420> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."
	Description['wsl0001-pqt'] = "Adds teleporter. Requires considerable Energy to activate.\n\nInstalls Teleporter"
    Description['wsl0001-dss'] = "Increases the speed at which the ACU repairs itself. Also increases hit points.\n\nHealth:+6000\nRegen Rate:+75"
	Description['wsl0001-adss'] = "Further increases the speed at which the ACU repairs itself. Also increases hitpoints.\n\nHealth:+20000\nRegen Rate:+150"
	Description['wsl0001-ras'] = "Increases ACU's resource generation.\n\nNew Mass Production:16\nNew Energy Production:3000"
	Description['wsl0001-eras'] = "Further increases ACU's resource generation.\n\nNew Mass Production:32\nNew Energy Production:6000"
	Description['wsl0001-aes'] = "Expands the number of available schematics and increases the ACU's build speed and maximum health.\n\nUnlock Tech 2 Construction\n+3000 Health\nArmour Regen:+20\nBuild Speed:+30"
	Description['wsl0001-ees'] = "Replaces the Tech 2 Engineering Suite. Expands the number of available schematics and further increases the ACU's build speed and maximum health.\n\nUnlock Tech 3 Construction\n+4000 Health\nArmour Regen:+15\nBuild Speed:+90"
	Description['wsl0001-cba'] = "Increases the damage inflicted by ACU's primary weapon. Adds area-of-effect damage.\n\nChronotron Cannon Damage:+300\nDamage Radius:+2"
	Description['wsl0001-nrf'] = "Automatically speeds up the repair speed of nearby units.\n\nInstalls Restoration Field\nRadius:15"
    Description['wsl0001-anrf'] = "Further speeds up the repair speed of nearby units.\n\nRadius:25"
	Description['wsl0001-hsa'] = "Increases main cannon's rate of fire and range. Also increases range of Overcharge.\n\nChronotron Cannon Rof:2\nNew Range:30"
	Description['wsl0001-tml'] = "Mounts a tactical cruise missile launcher onto the back of the ACU.\n\nInstalls Tactical Missile Launcher"
	Description['wsl0001-spsg'] = "Equips the ACU with a Personal Shield Generator. Requires energy to run.\n\nShield Health:24000\nShield Regen:35\nShield Type:Personal\nShield Mainntenance:250"
	Description['wsl0001-hspsg'] = "Upgrades the ACU's personal shield.\n\nShield Health:44000\nShield Regen:44\nShield Type:Personal\nShield Mainntenance:500"
	Description['wsl0001-hspsg_aa'] = "Enables a pair of Anti-Air Batteries.\n\nInstalls Olaris AA Artillery Cannons"
	Description['wsl0001-tml_aa'] = "Enables a pair of Anti-Air Batteries.\n\nInstalls Olaris AA Artillery Cannons"
	Description['wsl0001-torp'] = "Equips the ACU with a standard torpedo tube and sonar.\n\nInstalls Torpedo launcher"
	Description['wsl0001-tahu'] = "Adds a secondary cannon to the acu, increasing its overall damage.\n\nInstalls Aireau Bolter Cannon"