name = "Disperse Move"
uid = "Machd6c5-cd5c-4e34-b6cc-11503ed5e2da"
version = 10
description = "Adds a Disperse Move command that can be bound to a hotkey. Works like Spread Move, but only gives 1 order to each unit, evenly distributing them to their closest orders individually."
icon         = "/mods/Disperse Move/mod_icon.png"
author = "Mach"
contributors = "MrNukealizer"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
