name = "Pause replays at time"
version = 1
copyright = "Myxir"
description = "Adds a panel that allows pausing the replay at a certain game time"
author = "Myxir"
url = ""
uid = "20dec73e-d4b2-11e5-ab30-625662870761"
exclusive = false
ui_only = true
conflicts = {}
