layout = {
	['bar-top_scr_down'] = {left = 8, top = 8, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['bar-top_scr_over'] = {left = 8, top = 8, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['bar-top_scr_up'] = {left = 8, top = 8, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['bar-top_scr_dis'] = {left = 8, top = 8, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['bar-mid_scr_down'] = {left = 8, top = 14, width = 20, height = 8, leftOffset = 0, topOffset = 0, },
	['bar-mid_scr_over'] = {left = 8, top = 14, width = 20, height = 8, leftOffset = 0, topOffset = 0, },
	['bar-mid_scr_up'] = {left = 8, top = 14, width = 20, height = 8, leftOffset = 0, topOffset = 0, },
	['bar-mid_scr_dis'] = {left = 8, top = 14, width = 20, height = 8, leftOffset = 0, topOffset = 0, },
	['bar-bot_scr_down'] = {left = 8, top = 22, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['bar-bot_scr_over'] = {left = 8, top = 22, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['bar-bot_scr_up'] = {left = 8, top = 22, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['bar-bot_scr_dis'] = {left = 8, top = 22, width = 20, height = 8, leftOffset = 0, topOffset = 1, },
	['arrow-up_scr_down'] = {left = 0, top = 0, width = 36, height = 36, leftOffset = 0, topOffset = 1, },
	['arrow-up_scr_over'] = {left = 0, top = 1, width = 36, height = 32, leftOffset = 0, topOffset = 0, },
	['arrow-up_scr_up'] = {left = 1, top = 1, width = 36, height = 32, leftOffset = 1, topOffset = 0, },
	['arrow-up_scr_dis'] = {left = 1, top = 1, width = 36, height = 32, leftOffset = 1, topOffset = 0, },
	['arrow-down_scr_down'] = {left = 0, top = 3, width = 36, height = 36, leftOffset = 0, topOffset = 1, },
	['arrow-down_scr_over'] = {left = 0, top = 4, width = 36, height = 32, leftOffset = 0, topOffset = 0, },
	['arrow-down_scr_up'] = {left = 1, top = 4, width = 36, height = 32, leftOffset = 1, topOffset = 0, },
	['arrow-down_scr_dis'] = {left = 1, top = 4, width = 36, height = 32, leftOffset = 1, topOffset = 0, },
	['back_scr_top'] = {left = 4, top = 4, width = 28, height = 12, leftOffset = 0, topOffset = 1, },
	['back_scr_mid'] = {left = 4, top = 14, width = 28, height = 8, leftOffset = 0, topOffset = 0, },
	['back_scr_bot'] = {left = 4, top = 22, width = 28, height = 12, leftOffset = 0, topOffset = 1, },
}
