name = "Selection Deprioritizer"
version = 6
copyright = "nah"
description = "Prevents accidental selection of things like mobile T3 artillery. Reduces selection to domains. Deselects assisting shields and scouts. Edited by SpoCk0nd0pe and CodingSquirrel."
author = "partytime, changes by CodingSquirrel and Myxir"
uid = "bc7731b6-1416-11ea-8d71-362b9e155667"
selectable = false
exclusive = false
ui_only = true
