
--Aeon ACU Upgrades

Description['eal0001'] = "<LOC Unit_Description_0305> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."

Description['eal0001-exrzb1'] = "Jury Rigged Disruptor\nBy running additional power feeds and rapidly upgrading capacitors, upgrading the command chassis with a slightly enhanced main weapon can be useful when in a pinch. However, this system is automatically installed later if it is not needed earlier.\n\n+100 Disruptor Damage"
Description['eal0001-exrzb2'] = "Disruptor Amplifier\n\n+8 Disruptor Range\n+8 Overcharge Range"

Description['eal0001-exles1'] = "Improved Engineering\nThe standard engineering enhancement system focuses on improving resource allocation subsystems and build power.\n\nUnlock Tech 2 Construction\nBuild Speed 25\nMass Production 6\nEnergy Production 100"
Description['eal0001-exles2'] = "Advanced Engineering\nThe advanced engineering enhancement further improves resource yields and build power.\n\nUnlock Tech 3 Construction\nBuild Speed 75\nMass Production 16\nEnergy Production 500"
Description['eal0001-exles3'] = "Experimental Engineering\nThe experimental engineering enhancement system maximizes resource yields and building capability.\n\nUnlock Experimental Construction\nBuild Speed 210\nMass Production 28\nEnergy Production 1500\n10% faster movement"

Description['eal0001-exlce1'] = "Combat Engineering\nUnlike the standard engineering enhancement, combat engineering focuses on armor and regeneration. A chrono dampener area stun is also attached.\n\nUnlock Tech 2 Construction\n+10000 health\n25 Armor Regen\n20 Build Speed\nInstalls Chrono Dampener"
Description['eal0001-exlce2'] = "Assault Engineering\nFurther armor and regenerative capabilities; this upgrade makes the ACU capable of sustaining heavy damage. The chrono dampener gains increased range.\n\nUnlock Tech 3 Construction\n+20000 health\n60 Armor Regen\n45 Build Speed\n+8 Chrono Dampener Range"
Description['eal0001-exlce3'] = "Apocalyptic Engineering\nMaximum armor and regenerative capability.\n\nUnlock Experimental Construction\n+30000 health\n100 Armor Regen\n90 Build Speed"

Description['eal0001-exrtorp1'] = "Torpedo Launcher\nWhen forced to fight underwater, a run-of-the-mill torpedo system is a commander's best friend. Unfortunately, installing such systems hampers total combat effectiveness on land, but there are times when that is not a bad thing.\n\nInstalls Torpedo Launcher\nInstalls Anti-Torpedo System"
Description['eal0001-exrtorp2'] = "Improved Reloader\nIncreasing the torpedoes' rate of fire helps to slightly overcome anti-torpedo countermeasures as well as increasing destructive power output.\n\n+100 Disruptor Damage\n+120 Torpedo Damage\n+25% Torpedo Rate of Fire\nInstalls Disruptor Jury Rigging"
Description['eal0001-exrtorp3'] = "Advanced Warheads\nBy replacing the torpedoes' warheads with stronger shaped charges, the overall damage output of the system is increased exponentially, allowing the commander to become a menace to all seagoing vessels.\n\n+200 Disruptor Damage\n+1000 Torpedo Damage"

Description['eal0001-exramc1'] = "Dual Miasma Artillery\nThe miasma artillery system fires long range shells of corrosive materials at targets. These shells will airburst for maximum distribution of the corrosives and cause large amounts of damage to targets within the area.\n\nInstalls Dual Miasma Artillery"
Description['eal0001-exramc2'] = "Advanced Warhead Compression\nThrough advanced compression techniques, it has become possible to condense the corrosive materials into a extremely dense state. This allows for a much higher damage yield per shot than previous systems.\n\n+1500 Miasma Damage\nInstalls Disruptor Jury Rigging"
Description['eal0001-exramc3'] = "Improved Auto Loader\nWhile artillery tends to be very slow firing due to the need to constantly load extremely heavy shells into the system, it is possible to increase both weight handling as well as reload speed. This allows for larger warheads to be delivered to the firing systems at an increased speed.\n\n+3252 Miasma Damage\n+40% Miasma Rate of Fire"

Description['eal0001-exrgec1'] = "Phason Beam Cannon\nRather than the standard highly destructive beam cannons that are usually used in combat, the Aeon have created a light phason beam. This beam randomly rearranges the targets molecular structure, causing severe breakdowns in structural integrity.\n\nInstalls Phason Beam Cannon\n200 DPS"
Description['eal0001-exrgec2'] = "Dual Channel Booster\nThis installs a backup emitter system within the primary that can be alternated, preventing system shutdown due to continuous use. This effectively increases the damage output and range of the beam.\n\nPhason Damage 400DPS\n+13 Phason Range\nInstalls Disruptor Jury Rigging"
Description['eal0001-exrgec3'] = "Molecular Inducer\nBy running a pulsed current down the beam, it is possible to drastically alter the magnetic fields of the molecules being rearranged. This causes hull plating to literally tear itself apart.\n\nPhason Damage 600DPS\n+1 Phason Blast Radius"

Description['eal0001-exbsh1'] = "Shield Battery\nThis is a standard personal shield battery with a first-generation direct feed active regeneration system that enhances simple defenses.\n\n+8000 Shield Health\n+50 Active Shield Regen"
Description['eal0001-exbsh2'] = "Improved Shield Battery\nAn improvement over the original shield system that allows for both higher sustained regeneration and overall health.\n\n+15000 Shield Health\n+100 Active Shield Regen"
Description['eal0001-exbsh3'] = "Advanced Shield Battery\nBy further upgrading both power and emitter systems, shields with enormous regenerative properties and equally large strength are possible. Because of the nature of the regeneration systems, these shields are extremely efficient at diffusing beam weaponry.\n\n+23000 Shield Health\n+150 Active Shield Regen\nInstalls Tactical Missile Defense"
Description['eal0001-exbsh4'] = "Empty"

Description['eal0001-exbint1'] = "Electronic Enhancment\nThe need for battlefield intel has always been one of the higher priorities of most commanders. After all, if you are unaware of your enemy, then how do you fight them? This system is a simple extension of standard high-powered visual sensor systems.\n\n+24 Vision Radius\n+24 Omni Radius\nInstalls Tactical Missile Defense"
Description['eal0001-exbint2'] = "Farsight Optics Subsystem\nA prototype based off the designs for the full-sized optics facility; this subsystem can create a quantum mirror that allows you to temporarily view a location within a designated radius around the commander. This can be used to spot for artillery or to look before you leap when teleporting.\n\nInstalls Farsight Optics System"
Description['eal0001-exbint3'] = "Farjump Teleporter Subsystem\nWorking with the same modified recall device as the other factions and applying their greater quantum knowledge the Aeon have created a personal teleporter with a much higher maximum range than those of the other factions. This allows them to cover more ground in a single jump; however, it takes longer to charge the device.\n\nInstalls Teleporter"

Description['eal0001-exbbat1'] = "Maelstrom Generator\nWhile delving through research databanks, the plans for a quantum defense field system were discovered. While harmless to units designed to resist quantum disturbances, it is corrosive to everything else.\n\nInstalls Maelstrom Generator\n30 DPS at range of 21"
Description['eal0001-exbbat2'] = "Distortion Amplifier\nFurther development of the Maelstrom Generator. By adding amplified energy output systems, both the range and effect are increased.\n\nMaelstrom DPS increased to 50\nMaelstrom range increased to 28\nInstalls Tactical Missile Defense"
Description['eal0001-exbbat3'] = "Instability Enhancer\nThe addition of extra focusers and reflectors has allowed increased control over the instabilities that make up the field. Increases both field coverage and destructive potential.\n\nMaelstrom DPS increased to 75\nMaelstrom Range increased to 36"


--UEF ACU Upgrades

Description['eel0001'] = "<LOC Unit_Description_0303> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."

Description['eel0001-exrzb1'] = "Jury Rigged Zephyr\nBy running additional power feeds and rapidly upgrading capacitors, upgrading the command chassis with a slightly enhanced main weapon can be useful when in a pinch. However, this system is automatically installed later if it is not needed earlier.\n\n+100 Zephyr Damage\n+8 Zephyr Range\n+8 Overcharge Range"
Description['eel0001-exrzb2'] = "Empty"

Description['eel0001-exles1'] = "Improved Engineering\nThe standard engineering enhancement system focuses on improving resource allocation subsystems and build power.\n\nUnlock Tech 2 Construction\nBuild Speed 25\nMass Production 6\nEnergy Production 100"
Description['eel0001-exles2'] = "Advanced Engineering\nThe advanced engineering enhancement further improves resource yields and build power.\n\nUnlock Tech 3 Construction\nBuild Speed 75\nMass Production 16\nEnergy Production 500"
Description['eel0001-exles3'] = "Experimental Engineering\nThe experimental engineering enhancement system maximizes resource yields and building capability.\n\nUnlock Experimental Construction\nBuild Speed 210\nMass Production 28\nEnergy Production 1500\n10% faster movement"

Description['eel0001-exlce1'] = "Combat Engineering\nUnlike the standard engineering enhancement, combat engineering focuses on armor and regeneration. A chrono dampener area stun is also attached.\n\nUnlock Tech 2 Construction\n+10000 health\n25 Armor Regen\n20 Build Speed\nInstalls Flame Cannon"
Description['eel0001-exlce2'] = "Assault Engineering\nFurther expanding on the flame cannon and regen systems makes the commander even more dangerous in close combat.\n\nUnlock Tech 3 Construction\n+20000 health\n60 Armor Regen\n45 Build Speed\nFlame Cannon 250 DPS\n+8 Flame Cannon Range"
Description['eel0001-exlce3'] = "Apocalyptic Engineering\nMaximum armor and regenerative capability.\n\nUnlock Experimental Construction\n+30000 health\n100 Armor Regen\n90 Build Speed"

Description['eel0001-exrtorp1'] = "Torpedo Launcher\nWhen forced to fight underwater, a run-of-the-mill torpedo system is a commander's best friend. Unfortunately, installing such systems hampers the total combat effectiveness on land, but there are times when that is not a bad thing.\n\nInstalls Torpedo Launcher"
Description['eel0001-exrtorp2'] = "Improved Reloader\nIncreasing the torpedoes' rate of fire helps to slightly overcome anti-torpedo countermeasures as well as increasing destructive power output.\n\n+100 Zephyr Damage\n+55 Torpedo Damage\n+100% Torpedo Rate of Fire\nInstalls Zephyr Jury Rigging"
Description['eel0001-exrtorp3'] = "Advanced Warheads\nBy replacing the torpedoes' warheads with stronger shaped charges, the overall damage output of the system is increased exponentially, allowing the commander to become a menace to all seagoing vessels.\n\n+200 Zephyr Damage\n+425 Torpedo Damage"

Description['eel0001-exramc1'] = "Anti-Matter Cannon\nThis weapon system is a self-contained particle accelerator and mag bottle generator. When activated, the accelerator generates a small quantity of anti-matter that is contained within a mag bottle and launched at the target. The resulting explosion caused by matter meeting anti-matter releases enormous amounts of destructive force upon the target and the area surrounding it.\n\nInstalls Anti-Matter Cannon"
Description['eel0001-exramc2'] = "Improved Particle Accelerator\nBy constructing a more efficient particle accelerator for the anti-matter cannon, it is possible to generate more of this unstable substance between firing sequences. This allows the cannon to fire denser clouds of anti-matter at the target for a significant increase in destructive power.\n\n+1900 Anti-Matter Damage\n+1 Anti-Matter Blast Range\nInstalls Zephyr Jury Rigging"
Description['eel0001-exramc3'] = "Enhanced Mag Bottle\nWith the improvement of the accelerator, it is possible to generate more anti-matter than the current containment systems control. By improving the mag bottle equipment to emit a stronger containment field, it is possible to more than double the destructive power of this weapon system.\n\n+5500 Anti-Matter Damage\n+1 Anti-Matter Blast Range"

Description['eel0001-exrgec1'] = "Gatling Energy Cannon\nCombining a standard micro pellet gatling cannon with a high-energy subsystem creates a high powered gatling energy cannon with very little of the bloom effects that normally hinder longer ranged energy weapons. This weapon system is capable of bursts of sustained fire at longer ranges than normal energy weapons.\n\nInstalls Energy Gatling Cannon"
Description['eel0001-exrgec2'] = "Automatic Barrel Stabalizers\nOne of the largest problems with rotary gatling cannons is the potential for jamming caused by instability in the barrels, causing misalignment with ammunition feeds. This can be overcome with the addition of stabilizers and a control program to automatically adjust.\n\n+175 Gatling Damage\n+5 Gatling Range\nInstalls Zephyr Jury Rigging"
Description['eel0001-exrgec3'] = "Enhanced Power Subsystems\nBy increasing the power relays between the reactors and the barrels, it is possible to charge the pellets to such an extreme that the mere friction of the atmosphere causes them to glow white hot and inflict terrible kinetic impacts on targets.\n\n+550 Gatling Damage\n+5 Gatling Range"

Description['eel0001-exbsh1'] = "Shield Battery\nThis is a standard personal shield battery with a first-generation direct feed active regeneration system that enhances simple defenses.\n\n+7000 Shield Health\n+75 Active Shield Regen"
Description['eel0001-exbsh2'] = "Improved Shield Battery\nAn improvement over the original shield system that allows for both higher sustained regeneration and overall health.\n\n+13000 Shield Health\n+125 Active Shield Regen\nInstalls Energy Lance"
Description['eel0001-exbsh3'] = "Advanced Shield Battery\nBy further upgrading both power and emitter systems, shields with enormous regenerative properties and equally large strength are possible. Because of the nature of the regeneration systems, these shields are extremely efficient at diffusing beam weaponry.\n\n+20000 Shield Health\n+200 Active Shield Regen"
Description['eel0001-exbsh4'] = "Expanded Shield Bubble\nWith specialized shield equipment, it possible to expand a personal shield outward to cover an area. While this allows you to help protect nearby units, it also means it is easier to get under the shield.\n\nExpands Personal Shield into Bubble Shield"

Description['eel0001-exbint1'] = "Electronic Enhancment\nThe need for battlefield intel has always been one of the higher priorities of most commanders. After all, if you are unaware of your enemy, then how do you fight them? This system is a simple extension of standard high-powered visual sensor systems.\n\n+24 Vision Radius\n+24 Omni Radius\nInstalls Energy Lance"
Description['eel0001-exbint2'] = "Spysat Control Systems\nStaying ahead of the flow of battle during war is required for success. This system launches a small remote spy satellite with Omni capabilities to allow a commander to remotely monitor a flowing situation and respond properly. It is advised that you avoid enemy SMD launch platforms, as they have a habit of homing in on the sensor suites installed on this satellite.\n\nInstalls Spysat Control Systems\nInstalls Second Energy Lance"
Description['eel0001-exbint3'] = "Modified Recall Device\nInstalling adaptations to a commander's personal recall device allows for short burst teleportation. While the range is short, the teleport can power up faster than a longer-ranged version.\n\nInstalls Teleporter"

Description['eel0001-exbbat1'] = "Cluster Missile System\nPreferring to have weapon systems for all occasions, the installation of the cluster missiles gives the commander a high-range early bombardment system for dealing with minor fortifications.\n\nInstalls Cluster Missiles"
Description['eel0001-exbbat2'] = "Tactical Missile System\nWhile improving upon the cluster missiles' warheads, the ACU also can install a standard tactical missile launcher on its chassis that allows for precise targeting against larger health structures or units.\n\n+90 Cluster Missile Damage\nInstalls Manual Tactical Missiles"
Description['eel0001-exbbat3'] = "Tactical Nuclear System\nBy replacing the old tactical missiles with nuclear-tipped warheads, it is possible to bring low-end weapons of mass destruction to the battlefield. These miniature area killers are powerful anti-army weapons and are best used at long standoff ranges if possible.\n\n+250 Cluster Missile Damage\nInstalls \"Billy\" Tactical Nuclear Missiles"

Description['eel0001-led'] = "Engineering Drone acts as a secondary Engineer. Assists the ACU where applicable."
Description['eel0001-red'] = "Adds a second Engineering Drone. Requires an initial Engineering Drone."


--Cybran ACU Upgrades

Description['erl0001'] = "<LOC Unit_Description_0304> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."

Description['erl0001-exrzb1'] = "Jury Rigged Ripper\nBy running additional power feeds and rapidly upgrading capacitors, upgrading the command chassis with a slightly enhanced main weapon can be useful when in a pinch. However, this system is automatically installed later if it is not needed earlier.\n\n+100% Ripper Rate of Fire\n+8 Ripper Range\n+8 Overcharge Range"
Description['erl0001-exrzb2'] = "Empty"

Description['erl0001-exles1'] = "Improved Engineering\nThe standard engineering enhancement system focuses on improving resource allocation subsystems and build power.\n\nUnlock Tech 2 Construction\nBuild Speed 25\nMass Production 6\nEnergy Production 100"
Description['erl0001-exles2'] = "Advanced Engineering\nThe advanced engineering enhancement further improves resource yields and build power.\n\nUnlock Tech 3 Construction\nBuild Speed 75\nMass Production 16\nEnergy Production 500"
Description['erl0001-exles3'] = "Experimental Engineering\nThe experimental engineering enhancement system maximizes resource yields and building capability.\n\nUnlock Experimental Construction\nBuild Speed 210\nMass Production 28\nEnergy Production 1500\n10% faster movement"

Description['erl0001-exlce1'] = "Combat Engineering\nUnlike the standard engineering system, the combat engineering sacrifices the space that would normally enhance the resource allocation in order to install a cluster rocket system and improved regen systems.\n\nUnlock Tech 2 Construction\n+10000 health\n30 Armor Regen\n20 Build Speed\nInstalls Rocket Pack"
Description['erl0001-exlce2'] = "Assault Engineering\nFurther expanding on the rocket launcher and regen systems makes the commander even more dangerous in close combat.\n\nUnlock Tech 3 Construction\n+20000 health\n65 Armor Regen\n45 Build Speed\n+160 Rocket Pack Damage\n+8 Rocket Pack Range"
Description['erl0001-exlce3'] = "Apocalyptic Engineering\nWhile this system does not increase the destructive capabilities of the combat engineering weapon system, it does provide a significant increase in general regen for the command chassis.\n\nUnlock Experimental Construction\n+30000 health\n105 Armor Regen\n90 Build Speed"

Description['erl0001-exrtorp1'] = "Torpedo Launcher\nWhen forced to fight underwater, a run-of-the-mill torpedo system is a commander's best friend. Unfortunately, installing such systems hampers the total combat effectiveness on land, but there are times when that is not a bad thing.\n\nInstalls Torpedo Launcher"
Description['erl0001-exrtorp2'] = "Improved Reloader\nIncreasing the torpedoes' rate of fire helps to slightly overcome anti-torpedo countermeasures as well as increasing destructive power output.\n\n+50 Ripper Damage\n+75 Torpedo Damage\n+50% Torpedo Rate of Fire\nInstalls Ripper Jury Rigging"
Description['erl0001-exrtorp3'] = "Advanced Warheads\nBy replacing the torpedoes' warheads with stronger shaped charges, the overall damage output of the system is increased exponentially, allowing the commander to become a menace to all seagoing vessels.\n\n+100 Ripper Damage\n+400 Torpedo Damage"

Description['erl0001-exramc1'] = "EMP Array\nThis system uses triangulated lasers to superheat molecules within the target location, causing them to rapidly break down. The resulting explosion causes moderate damage to those near the blast and emits a strong electromagnetic pulse that temporarily overwhelms electronic control systems in most automated war machines.\n\nInstalls EMP Array"
Description['erl0001-exramc2'] = "Adjusted Crystal Matrix\nBy using crystals with far fewer flaws, the beams are allowed to focus on a much finer point. This allows the area's heat to increase faster and effect a larger portion of the local material, thus causing a larger detonation.\n\n+900 EMP Damage\n+1 EMP Stun Radius\n+5 EMP Range\nInstalls Ripper Jury Rigging"
Description['erl0001-exramc3'] = "Enhanced Laser Emitters\nTo increase efficiency of the system, the laser assembly needs to be upgraded and replaced, allowing for a higher throughput in power distribution. This allows a significantly larger amount of energy to be pushed through to the point of impact.\n\n+3300 EMP Damage\n+1 EMP Blast Radius\n+1 EMP Stun Radius\n+5 EMP Range"

Description['erl0001-exrgec1'] = "Heavy Microwave Laser\nThe Microwave Laser or \"Maser\" for short is a highly focused stream of microwaves directed at a target. This causes a massive breakdown in the targets electronic systems as well as superheating various materials, causing distortions and detonations within the target.\n\nInstalls Heavy Microwave Laser"
Description['erl0001-exrgec2'] = "Alternating Laser Assembly\nThis system pairs the original maser system with a twin that functions in alternating bursts of energy. While not noticeable to those viewing the system in action, it helps ensure higher power settings can be run while reducing maintenance demands caused by a single coil overheating.\n\n+150 Microwave Damage\nInstalls Ripper Jury Rigging"
Description['erl0001-exrgec3'] = "Superconductive Power Conduits\nBy running additional feeds directly to the main power systems, it is possible to overcharge the laser assembly and bring out the weapon's extremely destructive aspects. At these higher power levels, the system simply melts the armor off the target and flash fries their electronics.\n\n+600 Microwave Damage"

Description['erl0001-exbsh1'] = "Armor Plating\nAdditional armor is the easiest way to get additional defensive systems in battle.\n\n+7000 Health\nInstalls Two Anti-Air Lasers"
Description['erl0001-exbsh2'] = "Structural Integrity\nBy integrating several tiny force field generators, damage is localized.\n\n+11000 Health\nInstalls Two Additional Anti-Air Lasers"
Description['erl0001-exbsh3'] = "Nanite Materials\nThe use of nanite-laced materials makes it possible to increase the amount of armor the chassis can support.\n\n+18000 Health"
Description['erl0001-exbsh4'] = "Empty"

Description['erl0001-exbint1'] = "Electronic Enhancment\nThe need for battlefield intel has always been one of the higher priorities of most commanders. After all, if you are unaware of your enemy, then how do you fight them? This system is a simple extension of standard high-powered visual sensor systems.\n\n+24 Vision Radius\n+24 Omni Radius"
Description['erl0001-exbint2'] = "Electronic Countermeasures\nKnowing where your enemy is can win you the battle; however, keeping your enemy unaware of your location helps prevent you from losing. Electronic countermeasures use matching radar signals to cancel out your enemy's radar's ability to see you. While this system is not perfect, it is effective against standard radar systems.\n\nInstalls Personal Stealth"
Description['erl0001-exbint3'] = "Cloaking Subsystem\nUsing a combination of advanced computers and holographic systems, it is possible to create an advanced illusion of invisibility. While possible to still be picked up by radar systems, if not for preinstalled electronic countermeasures this system provides visual cloaking from all enemy units that do not have advanced sensor systems.\n\nInstalls Personal Cloaking"

Description['erl0001-exbbat1'] = "Actuator Replacment\nBy installing fine-tuned and highly responsive servos and actuators, it is possible for the command chassis to be accelerated without losing balance or stability. This increases its overall mobility on the battlefield.\n\nIncreases Movement Speed"
Description['erl0001-exbbat2'] = "Anti-Air Subsystem\nAircraft pose a significant threat to any commander on the battlefield; however, with the installation of highly precise anti-air laser systems, it is possible to negate some of the threat. If needed, the commander can also temporarily shift through a quantum rift to quickly teleport around the battlefield.\n\nInstalls Two Anti-Air Lasers\nInstalls Teleporter"
Description['erl0001-exbbat3'] = "Nano Regeneration Subsystem\nBy installing a large cache of nano machines and enough computer systems to help control them at extreme efficiency, it is possible to rapidly repair damage systems and get back into the battle before your opponents have the chance to do the same.\n\n+100 Armor Regen"


--Serephim ACU Upgrades

Description['esl0001'] = "<LOC Unit_Description_0420> Houses Commander. Combination barracks and command center. Contains all the blueprints necessary to build a basic army from scratch."

Description['esl0001-exrzb1'] = "Jury Rigged Chronoton\nBy running additional power feeds and rapidly upgrading capacitors, upgrading the command chassis with a slightly enhanced main weapon can be useful when in a pinch. However, this system is automatically installed later if it is not needed earlier.\n\nChronoton Damage 200DPS\n+8 Chronoton Range\n+8 Overcharge Range"
Description['esl0001-exrzb2'] = "Empty"

Description['esl0001-exles1'] = "Improved Engineering\nThis is a standard engineering enhancement system that focuses on improving resource allocation subsystems and build power.\n\nUnlock Tech 2 Construction\nBuild Speed 25\nMass Production 6\nEnergy Production 100"
Description['esl0001-exles2'] = "Advanced Engineering\nThis is a standard engineering enhancement system that focuses on improving resource allocation subsystems and build power.\n\nUnlock Tech 3 Construction\nBuild Speed 75\nMass Production 18\nEnergy Production 500"
Description['esl0001-exles3'] = "Experimental Engineering\nThis is a standard engineering enhancement system that focuses on improving resource allocation subsystems and build power.\n\nUnlock Experimental Construction\nBuild Speed 225\nMass Production 36\nEnergy Production 1500"

Description['esl0001-exlce1'] = "Combat Engineering\nUnlike the standard engineering, combat engineering enhances the armor and regen of the ACU and installs area regeneration systems that heal your nearby units.\n\nUnlock Tech 2 Construction\n+10000 health\n25 Armor Regen\n20 Build Speed\nInstalls Regen Aura"
Description['esl0001-exlce2'] = "Assault Engineering\nFurther upgrades to armor and regeneration give the command chassis an incredible ability to repair itself and engage in combat.\n\nUnlock Tech 3 Construction\n+20000 health\n60 Armor Regen\n45 Build Speed"
Description['esl0001-exlce3'] = "Apocalyptic Engineering\nThis further increases the area regen capabilities of the ACU and provides a significant increase in armor and regen for the command chassis.\n\nUnlock Experimental Construction\n+30000 health\n100 Armor Regen\n90 Build Speed\nUpgrades the Regen Aura"

Description['esl0001-exrtorp1'] = "Torpedo Launcher\nWhen forced to fight underwater, a run-of-the-mill torpedo system is a commander's best friend. Unfortunately, installing such systems hampers the total combat effectiveness on land, but there are times when that is not a bad thing.\n\nInstalls Torpedo Launcher"
Description['esl0001-exrtorp2'] = "Improved Reloader\nIncreasing the torpedoes' rate of fire helps to slightly overcome anti-torpedo countermeasures as well as increasing destructive power output.\n\n+100 Chronoton Damage\n+25 Torpedo Damage\n+100% Torpedo Rate of Fire\nInstalls Chronoton Jury Rigging"
Description['esl0001-exrtorp3'] = "Advanced Warheads\nBy replacing the torpedoes' warheads with stronger shaped charges, the overall damage output of the system is increased exponentially, allowing the commander to become a menace to all seagoing vessels.\n\n+200 Chronoton Damage\n+475 Torpedo Damage"

Description['esl0001-exramc1'] = "Quantum Storm Cannon\nBy creating miniature ruptures in the fabric of space and letting uncontrolled quantum energies out, the storm cannon can cause a significant amount of damage to any stationary target. However, if the target is able to move fast enough, it can quickly emerge from within reach of those destructive energies.\n\nInstalls Quantum Storm Cannon"
Description['esl0001-exramc2'] = "Power Conversion Enhancer\nBy dumping a significant amount of energy into the weapon system, it is possible to open a slightly larger rift at farther distances. This gives the weapon the ability to hit targets which high-end weaponry normally can not.\n\n+1400 Storm Damage\n+1 Storm Blast Radius\n+5 Storm Range\nInstalls Chronoton Jury Rigging"
Description['esl0001-exramc3'] = "Advanced Distortion Algorithms\nWith a little creative energy manipulation, the storm cannon can be set up so that when it detonates, it not only opens a rift, but helps draw destructive energies from it. This causes a more rapid degradation in nearby enemy units over the course of the detonation.\n\n+5800 Storm Damage\n+5 Storm Range"

Description['esl0001-exrgec1'] = "Plasma Gatling Cannon\nUsing a cluster of micro barrels to chamber and discharge plasma bolts, the Seraphim have created a very powerful plasma gatling cannon. However, while it is extremely dangerous, it also suffers from bloom effects, limiting its effective range.\n\nInstalls Plasma Gatling Cannon"
Description['esl0001-exrgec2'] = "Phased Energy Fields\nBy phasing the shots slightly into a higher frequency, the gatling system gains a slight increase in range as well as causing more damage to the target. This allows the weapon to move between targets more easily.\n\n+225 Gatling Damage\n+5 Gatling Range\nInstalls Chronoton Jury Rigging"
Description['esl0001-exrgec3'] = "Secondary Power Feeds\nRunning additional power feeds to the small plasma chambers allows for a higher charge and faster cycling time. This causes more powerful shots in rapid succession, causing extreme damage to the target.\n\n+650 Gatling Damage"

Description['esl0001-exbsh1'] = "Basic Lambda Field Emitter\nBorn from a mastery of quantum mechanics, the Lambda system distorts the very fabric of space around the command unit. This field, depending on the strength of the distortions, has the capability to deflect incoming projectiles off their flight path.\n"
Description['esl0001-exbsh2'] = "Enhanced Lambda Emitters\nBy enhancing the energy-to-mass output of the Lambda systems, the field becomes much stronger at deflecting projectiles. It has also been noted that occasionally a micro rift will open just long enough to swallow incoming projectiles.\n"
Description['esl0001-exbsh3'] = "Advanced Lambda Emitters\nAfter further analysis of rifts formed by previous Lambda designs, a control program has been designed to more efficiently create these rifts. These additional rifts swallow incoming projectiles very effectively but still have no effect on beam weapons.\n"
Description['esl0001-exbsh4'] = "Empty"

Description['esl0001-exbint1'] = "Electronic Enhancment\nThe need for battlefield intel has always been one of the higher priorities of most commanders. After all, if you are unaware of your enemy, then how do you fight them? This system is a simple extension of standard high-powered visual sensor systems.\n\n+24 Vision Radius\n+24 Omni Radius\nInstalls Lambda Field Emitters"
Description['esl0001-exbint2'] = "Personal Teleporter Subsystem\nInstalling a compact personal teleport subsystem allows the commander to move rapidly about the battlefield, providing assistance as needed. This pack also installs light anti-air defensive systems to help protect the commander from airborne threats.\n\nInstalls Teleporter\nInstalls Two Anti-Air Cannons\nInstalls Enhanced Lambda Emitters"
Description['esl0001-exbint3'] = "Phasic Cloaking Subsystem\nThis is an advanced version of the phasic cloaking systems used by light scouts to monitor enemies. As long as the commander is motionless and not making use of high energy systems such as the personal teleporter or weapon overcharge, the commander should be concealed from both enemy eyes and sensors.\n\nInstalls Phasic Cloaking Subsystems"

Description['esl0001-exbbat1'] = "Improved Combat Armor\nThis general enhancement adds armor and increases the range of the command unit's overcharged cannon shots.\n\n+10000 Health\nOvercharge Range 45\nInstalls Basic Lambda Field Emitter"
Description['esl0001-exbbat3'] = "Ultimate Combat Systems\nThis upgrade grants additional armor and extends the range of the overcharge cannon significantly.\n\n+20000 Health\nOvercharge Range 60"
