layout = {
	['logo-aeon_btn_over_sel'] = {left = 5, top = 1, width = 101, height = 111, },
	['logo-aeon_btn_sel'] = {left = 5, top = 1, width = 101, height = 111, },
	['logo-aeon_btn_over'] = {left = 0, top = 0, width = 108, height = 112, },
	['logo-aeon_btn_up'] = {left = 10, top = 9, width = 91, height = 96, },
	['logo-aeon_btn_dis'] = {left = 10, top = 9, width = 91, height = 96, },
	['logo-cybran_btn_over_sel'] = {left = 0, top = 0, width = 108, height = 112, },
	['logo-cybran_btn_sel'] = {left = 0, top = 0, width = 108, height = 112, },
	['logo-cybran_btn_over'] = {left = 6, top = 8, width = 98, height = 97, },
	['logo-cybran_btn_up'] = {left = 10, top = 9, width = 90, height = 96, },
	['logo-cybran_btn_dis'] = {left = 10, top = 9, width = 90, height = 96, },
	['logo-uef_btn_over_sel'] = {left = 0, top = 0, width = 108, height = 112, },
	['logo-uef_btn_sel'] = {left = 0, top = 0, width = 108, height = 112, },
	['logo-uef_btn_over'] = {left = 10, top = 9, width = 90, height = 96, },
	['logo-uef_btn_up'] = {left = 5, top = 2, width = 95, height = 110, },
	['logo-uef_btn_dis'] = {left = 10, top = 9, width = 90, height = 96, },
}
