name = "LOUD Unit Additions"
uid = "fffffffe-6e98-4864-9599-4133236eea7a"
version = 1.1
copyright = "None"
description = "Integrates additional experimentals, shields, defenses & utility buildings.  All are fully LOUD balanced and AI functional."
author = "H Katzmarek -- Sprouto"
url = ""
icon = "/mods/LOUD.bmp"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
