name = "BlackOps Unleashed Units for LOUD"
uid = "9e8ea941-c306-4751-b367-a11000000502"
version = 7.15
copyright = "Lt_hawkeye"
description = "BlackOps Unleashed Unitpack for LOUD"
author = "Lt_hawkeye"
url = ""
icon = "/mods/BlackOpsUnleashed/icons/yoda_icon.bmp"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
