name = "V2 FA Sequentially upgrading extractors"
uid = "D000E905-1E97-420D-8ED9-DF083282F59D"
version = 4
copyright = "Copyright © 2006, Gas Powered Games"
description = "Sequentially upgrades mass extractors and other buildings."
author = "uXs norem mgmetal13"
url = "http://www.eskimo.com/blah"
icon = "/mods/V2ExtractorUpgrades/Sequentialmexup.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
