name = "BlackOps Adv Command Units for LOUD"
uid = "9e8ea941-c306-4751-b367-e00000000302"
version = 7.15
copyright = "2009 Exavier Macbeth"
description = "Redesigns ACU Upgrades for More Options. Increases ACUs power to experimental levels as upgraded."
author = "Exavier Macbeth"
url = ""
icon = "/mods/BlackopsACUs/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
